### ISSUE TITLE
in the new_visus release we do not have the toggle about refresh of the data.

### ISSUE THREAD

**Issue by pascucci** [sci-visus/visus-issues#197]
We use to have refresh now and the toggle on refresh automatically when a view changes.
The latter is not there anymore but was useful.

**Comment by scrgiorgio** [comment]
You need to double click on the glcamera and check/uncheck "bPublishOnCameraChange".
Consider that now we can have multiple glcameras, and so each camera can be the master one (i.e. lead when the refresh has to happen)
