### ISSUE TITLE
Visus Startup windows download startup error/ missing dll.

### ISSUE THREAD

**Issue by AaronBehunin** [sci-visus/visus-issues#199]
1.download Visus viewer from (http://atlantis.sci.utah.edu/builds/ViSUS/win64/2015-01-09/ViSUS-LIB-new_develop-win64-juce-opengl-8e0658d.zip) this is a nightly build.

2.open bin/visusviewer.exe

3. App refuses to open/  requiers MSVCP120.dll
![error](https://cloud.githubusercontent.com/assets/10467750/5685640/63a8ed5c-97f9-11e4-979d-d89c995b0ad4.jpg)

**Comment by scrgiorgio** [comment]
Maybe you didn't install "Microsoft Visual C++ Redistributable Package (x64) Visual Studio 2013".

buildbot binaries are just zipped *.EXE and *.DLL files .. it's not an installer.

We had  some kind of "Visus Windows MSI installer"... maybe you want to (*) give a look to visuscpp\install\InstallShield, (*) try to use and/or fix it? It's a long time I'm not using it.

**Comment by AaronBehunin** [comment]
Yes that did the trick for me
