### ISSUE TITLE
Open URL error

### ISSUE THREAD

**Issue by AaronBehunin** [sci-visus/visus-issues#201]
Windows x64
defalut URl wont open 

1. file/open url/press ok

program crashes

**Comment by scrgiorgio** [comment]
Is the default url:

http://atlantis.sci.utah.edu/mod_visus?dataset=2kbit1

I just did it and it's working fine for me... can you try again and if it's still crashing send me the call stack?

**Comment by AaronBehunin** [comment]
Working now for me
