### ISSUE TITLE
Visus x64 Bookmark Missing data

### ISSUE THREAD

**Issue by AaronBehunin** [sci-visus/visus-issues#203]
It Appears that the Alstom boiler bookmark under CIBC is missing data.   

All that shows under volume is a black slice.

![boiler](https://cloud.githubusercontent.com/assets/10467750/5744755/5451b5e0-9bd8-11e4-9d64-d7a837e3d75a.png)

**Comment by scrgiorgio** [comment]
"Alstom boiler bookmark"... is it a atlanta bookmark or local bookmark?
where is the IDX file stored?
what is the url of the dataset? 
what is the path of binary files? 
have you checked the permissions?
etc etc

**Comment by scrgiorgio** [comment]
Closing since I don't have enough details
