### ISSUE TITLE
X64 openGL bookmark link broken

### ISSUE THREAD

**Issue by AaronBehunin** [sci-visus/visus-issues#204]
Clicking bookmarks/ Kaust/ Flame    returns openfile error.

![flame](https://cloud.githubusercontent.com/assets/10467750/5745753/dc997c56-9bdf-11e4-87c8-73d38dc01e5a.png)

**Comment by scrgiorgio** [comment]
Again, what is the full url?
Is the Kaust server up and running?
can you telnet on port 80?

**Comment by scrgiorgio** [comment]
Closing since don't see any answer.

BTW it's absolutely fine if Visus cannot find a file and pops us a message box.

Usually you double check the visus.config and see what's going on (example: wrong name, non-existing dataset, xml error etc etc)
