### ISSUE TITLE
windows x64 opengl  cant remove extractors

### ISSUE THREAD

**Issue by AaronBehunin** [sci-visus/visus-issues#206]
you have the ability to add an extractor but not delete, therefore creating overlapping layers of data with no way to remove them
![exctrating](https://cloud.githubusercontent.com/assets/10467750/5764296/aa5cd082-9ca5-11e4-9d0c-ce9f2a0fadfa.png)

(volume and slice exctractors but no reference in left-hand list)

**Comment by scrgiorgio** [comment]
Right click on the Query and "Remove Node"?

NOTE: you need to expand the Dataset node to actually see the query (i.e. exractor)

**Comment by AaronBehunin** [comment]
Found expand arrow, but against dark gray background it is very hard to see.   Can we possibly change the color?
