### ISSUE TITLE
x64 windows opengl right-click undo  dosen't do anything

### ISSUE THREAD

**Issue by AaronBehunin** [sci-visus/visus-issues#207]
Right-click on a node and selecting undo doesn't appear to change anything

**Comment by AaronBehunin** [comment]
Same thing when right-clicking on a node and selecting redo.

**Comment by scrgiorgio** [comment]
Fixed https://github.com/sci-visus/nvisusio/commit/ffa6a8925c6764720a98ab2014022b7c6c153739

There was a problem with the right-click: it was inserting a new "select node" action.
Now I don't show Undo/Redo in a popup menu
