### ISSUE TITLE
x64 windows opengl / Remove node doesn't remove image

### ISSUE THREAD

**Issue by AaronBehunin** [sci-visus/visus-issues#208]
When removing a camera node the image still displays
![remove_cameranode](https://cloud.githubusercontent.com/assets/10467750/5764832/e8691c88-9ca9-11e4-898b-b1ba9892cba0.png)

**Comment by scrgiorgio** [comment]
Fixed:
https://github.com/sci-visus/nvisusio/commit/588100044fb80cd6d4af33df73bd3b72b8d380c7
