### ISSUE TITLE
manipulator not shown when volume is selected

### ISSUE THREAD

**Issue by cchriste** [sci-visus/visus-issues#210]
It appears the manipulator shown when the volume is selected no longer shows up in new_develop. Only the query manipulator is ever shown. This is important for multi-volume scenes.

![data_manip](https://cloud.githubusercontent.com/assets/1260945/5828352/14e91f74-a114-11e4-89b4-5e05672239ae.png)

**Comment by scrgiorgio** [comment]
See my Post in Visus Google Groups about Multiple Queries, you need to insert a new TransformNode
