### ISSUE TITLE
Windows x64 opengl/   Mirrors don't do anything in 3d pictures.

### ISSUE THREAD

**Issue by AaronBehunin** [sci-visus/visus-issues#211]
right click glcamera/ select either mirror x or mirror y.  Nothing happens.  

If this action is not supported in 3D renders then don't make it available.

**Comment by scrgiorgio** [comment]
Done
https://github.com/sci-visus/nvisusio/commit/560613f7c7dc2de8a01a250056b6aee485e9ce6f
