### ISSUE TITLE
windows x64 opengl/  fit best not working in 3d pictures

### ISSUE THREAD

**Issue by AaronBehunin** [sci-visus/visus-issues#212]
Right clicking glcamera and selecting "fit best" works in 2d renders but not 3d ones.

Fit best is supposed to resize the render so that it uses as much render window  as possible, so this feature should work with 3d renders also.

**Comment by scrgiorgio** [comment]
It's working for me.
I think I already fixed it some time ago, but not sure.
Can you double check?

**Comment by scrgiorgio** [comment]
I checked again. It seems to work just fine.
Could be a problem specific for some dataset?
Closing the issue.
