### ISSUE TITLE
windows x64 openGL / Bad bookmark 

### ISSUE THREAD

**Issue by AaronBehunin** [sci-visus/visus-issues#213]
1.Click bookmarks,
2. mouse over atlantis
3. mouse over arup
4. click ldav2d MIDX

What shows is a black rectangle.
Not a very good demo file.
![bad](https://cloud.githubusercontent.com/assets/10467750/5906473/b960c1f6-a54c-11e4-82bb-ca387b133ba0.png)

**Comment by scrgiorgio** [comment]
Cannot reproduce.
I need the real url (from visus.config) not the alias.

BTW I'm not the right person for debugging what's  wrong with datasets. 
Cameron? Is Arup yours?

**Comment by AaronBehunin** [comment]
http://atlantis.sci.utah.edu/mod_visus?dataset=ldav2d

**Comment by scrgiorgio** [comment]
The data is there and served well.
It's a top white stripe with a bottom black area.
I may agree that it's not a good demo, but it's not an "issue".

**Comment by cchriste** [comment]
We should create an issue type for dataset problems in Redmine (currently
there are Bug, Feature, and Support).

Because this is a valid issue to be noted: in fact there was a problem
converting the original data. We still have the original data and can
re-convert when time permits.
