### ISSUE TITLE
windows x64 openGL / Bad bookmark2

### ISSUE THREAD

**Issue by AaronBehunin** [sci-visus/visus-issues#214]
1. Click bookmarks
2.  mouse over atlantis
3.  mouseover arup
4. click rbccase4_sub

Image is not layered correctly.
![bad1](https://cloud.githubusercontent.com/assets/10467750/5907402/7ed1d0be-a553-11e4-8944-1f7dc562092e.png)

**Comment by scrgiorgio** [comment]
Cannot reproduce.
I need the real url (from visus.config) not the alias.

**Comment by AaronBehunin** [comment]
here it is:

http://atlantis.sci.utah.edu/mod_visus?dataset=rbccase4_sub

**Comment by scrgiorgio** [comment]
for what I can see, the data is there and it's served well.
Maybe it's a problem in the visusconvert?
