### ISSUE TITLE
windows x64 opengl / broken bookmarks 

### ISSUE THREAD

**Issue by AaronBehunin** [sci-visus/visus-issues#215]
All the bookmarks under the CIBC folder are all broken.  They had been working fine previously.  

Note: one of the bookmarks attempts to  load upon startup.

**Comment by scrgiorgio** [comment]
Don't know what to do.
Cameron: CIBC is yours?
Are they still 'up'?

**Comment by AaronBehunin** [comment]
The urls for the bookmarks in question are 

(From visus.config)
CIBC:
http://remus.chpc.utah.edu:8080/mod_visus?dataset=single_coal_jet-time
http://remus.chpc.utah.edu:8080/mod_visus?dataset=single_coal_jet
http://remus.chpc.utah.edu:8080/mod_visus?dataset=alstom_boiler

Kaust:
http://fen4.hpc.kaust.edu.sa/mod_visus?dataset=flame
http://fen4.hpc.kaust.edu.sa/mod_visus?dataset=KB-E0010

**Comment by scrgiorgio** [comment]
Don't open issues about a missing dataset.
 
99% of the time the problem is related to a wrong visus.config or a not-mounted dataset
.
If so, correct the visus.config and send an email to Visus google group simply asking to correct the wrong urls (and please suggest corrections).

To debug why a dataset is now working:

wget http://remus.chpc.utah.edu:8080/mod_visus?action=list

<datasets>
        <group name="sc14">
                <dataset name="alstom_boiler-CC" permissions="public" url="http://$(hostname):$(port)/mod_visus?action=readdataset&amp;dataset=alstom_boiler-CC" />
                <dataset name="alstom_boiler-CC-Vec3" permissions="public" url="http://$(hostname):$(port)/mod_visus?action=readdataset&amp;dataset=alstom_boiler-CC-Vec3" />
                <dataset name="single_coal_jet-CC" permissions="public" url="http://$(hostname):$(port)/mod_visus?action=readdataset&amp;dataset=single_coal_jet-CC" />
                <dataset name="turbulence-64-f10" permissions="public" url="http://$(hostname):$(port)/mod_visus?action=readdataset&amp;dataset=turbulence-64-f10" />
                <dataset name="turbulence-64-f1" permissions="public" url="http://$(hostname):$(port)/mod_visus?action=readdataset&amp;dataset=turbulence-64-f1" />
                <dataset name="turbulence-256-f100" permissions="public" url="http://$(hostname):$(port)/mod_visus?action=readdataset&amp;dataset=turbulence-256-f100" />
                <dataset name="turbulence-256-f1" permissions="public" url="http://$(hostname):$(port)/mod_visus?action=readdataset&amp;dataset=turbulence-256-f1" />
                <dataset name="temporal_jet" permissions="public" url="http://$(hostname):$(port)/mod_visus?action=readdataset&amp;dataset=temporal_jet" />
                <dataset name="temporal_jet-big" permissions="public" url="http://$(hostname):$(port)/mod_visus?action=readdataset&amp;dataset=temporal_jet-big" />
                <dataset name="temporal_jet-big-GZ" permissions="public" url="http://$(hostname):$(port)/mod_visus?action=readdataset&amp;dataset=temporal_jet-big-GZ" />
                <dataset name="temporal_jet-bigger" permissions="public" url="http://$(hostname):$(port)/mod_visus?action=readdataset&amp;dataset=temporal_jet-bigger" />
        </group>
</datasets>

(NOTE: you need to know the hostname, the port, and use action=list).

**Comment by cchriste** [comment]
Hi Giorgio,
I asked Aaron to file bugs about everything, so please accept my apology
for the misunderstanding.
Ciao,Cameron
