### ISSUE TITLE
windows x64 opengl/  axis shifts cause 2d images to dissapear

### ISSUE THREAD

**Issue by AaronBehunin** [sci-visus/visus-issues#216]
1. open 2d render of choice
2. right click glcamera
3. select either x axis, y axis, or z axis

If this feature is not to be used in 2d renders then get rid of it.

**Comment by scrgiorgio** [comment]
Done
https://github.com/sci-visus/nvisusio/commit/e6c41a8d13cc026df1e0f98f361c2778beb2cb6c
