### ISSUE TITLE
Windows x64 opengl   Black lines when using bdebugFrustum

### ISSUE THREAD

**Issue by AaronBehunin** [sci-visus/visus-issues#217]
1. double-click glcamera
2. select bdebugGrustum 
3. Manipulate render with mouse

![bad2](https://cloud.githubusercontent.com/assets/10467750/5926014/a58c70b4-a61c-11e4-930f-17a5f82a4154.png)

**Comment by AaronBehunin** [comment]
Note that i do not know what this function is supposed to do.
Whoever does please comment.

**Comment by scrgiorgio** [comment]
Example:

(*) you look a 3d scene from a particular viewpoint

(*) you want to debug if the view-dependent stuff is really working == what is the intersection of the current frustum with the QueryNode-s around? 

To simplify the debugging you check "bDebugFrustum", then you move the camera/viewpoint around but you still see the old frustum and query-nodes intersections

Maybe we should disable this feature in release mode
