### ISSUE TITLE
windows x64 opengl/ undo goes to point in between mouse click

### ISSUE THREAD

**Issue by AaronBehunin** [sci-visus/visus-issues#218]
While manipulating an extractor (ex a slice)

When undoing(ctrl+z) an action the program regresses to points between mouse click and mouse release.

It uses up a lot of ram to keep track of render states inside one manipulation.

**Comment by scrgiorgio** [comment]
"It uses up a lot of ram to keep track of render states inside one manipulation."

not getting it..why you are saying "render states"?

**Comment by AaronBehunin** [comment]
what i mean is when you manipulate the render with the mouse, the program saves all renders between clicking the mouse and releasing the mouse.  when you click undo the render goes to one between clicks.  Its not necessarily a bug, but it does use up RAM.

in comparison, MS paint does not do this.

**Comment by cchriste** [comment]
Agreed with @scrgiorgio that "collapsing" actions is necessary for the user interface. It doesn't make sense for undo/redo to replay every UI update during manipulation. 

Changing this to Feature Request and assigning to Giorgio.

**Comment by scrgiorgio** [comment]
This issue was moved to sci-visus/nvisusio#510
