### ISSUE TITLE
windows x64 opengl /double-click in right click

### ISSUE THREAD

**Issue by AaronBehunin** [sci-visus/visus-issues#219]
When you right click a node, the action that double-clicking the node should be listed.

For example when right clicking a time setting in a volume node, a option to edit should appear and function just as double-clicking the time setting would.

**Comment by AaronBehunin** [comment]
Similar how you can open a folder/program in Windows by right-clicking the icon and selecting open.

**Comment by scrgiorgio** [comment]
Good point.
Done: https://github.com/sci-visus/nvisusio/commit/bcc7e8ada71a6cfc59529c62a32fa5b27bd2f6c4
