### ISSUE TITLE
windows x64 opengl /  Editing From and To values under time doesn't do anything 

### ISSUE THREAD

**Issue by AaronBehunin** [sci-visus/visus-issues#221]
open dataset with time factor 
click arrow next to folder node
double click time node
make sure value is set to 0
change From or To value to point in between 0 and current To.
press play.

From and/or to will reset to default values and play as normal. 

We need the play feature to recognize the new values.

**Comment by scrgiorgio** [comment]
Done: https://github.com/sci-visus/nvisusio/commit/bcc7e8ada71a6cfc59529c62a32fa5b27bd2f6c4

NOTE: the time is a weird beast. Internally we could have some non-linear timesteps. But the gui stuff is not handling it well.
