### ISSUE TITLE
windows x64 opengl / progression node missing features.  

### ISSUE THREAD

**Issue by AaronBehunin** [sci-visus/visus-issues#224]
Open any dataset.
click arrow next to file node
double click progression

edit window only has sliding bar that doesn't seem to do anything 

![blank_edit_2](https://cloud.githubusercontent.com/assets/10467750/6006375/de784cb4-aac6-11e4-957d-fa9dfe86341d.png)

**Comment by scrgiorgio** [comment]
Progression at dataset level is useful only for very special cases.
Use Slice1/progression instead.

PS To make clear what's happening:
(*) Look at the dataflow. Slice1/progression is CONNECTED to Slice1 input port
(*) Remove Slice1/progression
(*) See again the dataflow. The old DISCONNECTED dataset/progression is now CONNECTED to Slice1 input port (== the slider will do something)
