### ISSUE TITLE
windows x64 opengl / enable_viewdep node missing features.  

### ISSUE THREAD

**Issue by AaronBehunin** [sci-visus/visus-issues#225]
open dataset
click arrow next to file node
double click enable_viewdep 

Edit window has unmarked button that doesn't appear to do anything.

![blank_edit_3](https://cloud.githubusercontent.com/assets/10467750/6007420/b212a61c-aace-11e4-8938-658a4c80239b.png)

**Comment by scrgiorgio** [comment]
dataset/enable_viewdep is useful only when (1) you have multiple queries (2) you remove all query/enable_viewdep (3) you use the 'shared' dataset/enable_viewdep

otherwise use Volume1/enable_viewdep
