### ISSUE TITLE
windows x64 opengl /  Negative extractor values

### ISSUE THREAD

**Issue by AaronBehunin** [sci-visus/visus-issues#226]
1. open 3d dataset of choice
2.  click arrow next to file node
3.   click on default extractor node.  
4. in window manipulate colored boxes to give x, y or z values negative numbers.  

Several bugs arise from the ability to go to negative values in rendering negative extraction areas.

**Comment by AaronBehunin** [comment]
known bugs:
1. Manipulation graphics in render disappear, leaving you unable to undo by manipulating render.
![negative1](https://cloud.githubusercontent.com/assets/10467750/6084096/03700c36-ade3-11e4-881f-ad46671d5699.png)





2. You can undo the negative scaling by Ctrl-z. however render becomes distorted.
![negative2](https://cloud.githubusercontent.com/assets/10467750/6084113/2506d456-ade3-11e4-95b5-f606d88fc871.png)






3.  while negative scales present, you are unable to open position node edit window.

**Comment by AaronBehunin** [comment]
Note:      if extractor has been rotated, when going into negative scaling, scale window will loop and start increasing.  However, the bugs 1 and 2 still apply.

**Comment by AaronBehunin** [comment]
Happens to all extractors

**Comment by scrgiorgio** [comment]
Maybe fixed: https://github.com/sci-visus/nvisusio/commit/f0663d0734d5d908c1f531b0cba136904846c19a

can you double check?

**Comment by AaronBehunin** [comment]
this no longer produces bugs
