### ISSUE TITLE
Suggestion box

### ISSUE THREAD

**Issue by AaronBehunin** [sci-visus/visus-issues#227]
Don't know where else to put this, but if anyone has a suggestion on how to improve Visus non-bug wise, post it here.

**Comment by AaronBehunin** [comment]
I think an extractor in the shape of a circle or sphere would improve the quality of the program.

**Comment by scrgiorgio** [comment]
Please don't use visus-issues for non-bug stuff.

Use: 

  https://groups.google.com/forum/?hl=IT#!forum/visus_users
