### ISSUE TITLE
statistics node assert failed when force refresh

### ISSUE THREAD

**Issue by cchriste** [sci-visus/visus-issues#231]
1) open default 3d volume
2) add statistics node to slice
3) force refresh
-> assertion

platform tested: osx

output: 
nothing indicating an error

stack:
#0	0x0000000100724019 in Visus::Application::breakInDebugger() at /Users/cam/code/nvisus/visuscpp/../visuscpp/kernel/application/visus_application.cpp:742
#1	0x0000000100996d70 in Visus::VisusAssertFailed(char const*, int, char const*) at /Users/cam/code/nvisus/visuscpp/kernel/visus_kernel.cpp:25
#2	0x000000010087b57d in Visus::ObjectFactory::getPortableTypeName(Visus::Object const&) at /Users/cam/code/nvisus/visuscpp/../visuscpp/kernel/core/visus_object.h:172
#3	0x000000010089ac5c in Visus::StringTreeEncoder::encode(Visus::Object*) at /Users/cam/code/nvisus/visuscpp/kernel/core/visus_stringtree.cpp:309
#4	0x00000001008960d3 in Visus::XmlEncoder::encode(Visus::Object const*) at /Users/cam/code/nvisus/visuscpp/kernel/core/visus_stringtree.cpp:401
#5	0x00000001008e45d9 in Visus::MVCModel::beginUpdate(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >) at /Users/cam/code/nvisus/visuscpp/kernel/mvc/visus_mvcmodel.cpp:264
#6	0x0000000100093e3d in Visus::StatisticsNode::messageHasBeenPublished(std::__1::shared_ptr<Visus::DataflowMessage> const&) at /Users/cam/code/nvisus/visuscpp/appkit/nodes/visus_statisticsnode.cpp:241
#7	0x00000001005c1559 in Visus::Dataflow::dispatchPublishedMessages() at /Users/cam/code/nvisus/visuscpp/dataflow/visus_dataflowclass.cpp:235
#8	0x00000001001a2fdc in Visus::ViewerWindow::onTimer(Visus::Void) at /Users/cam/code/nvisus/visuscpp/appkit/viewer/visus_viewer_window.cpp:691
#9	0x00000001001bc27f in Visus::Private::InstanceSlot<Visus::ViewerWindow, Visus::Void>::receiveSignal(Visus::Void) at /Users/cam/code/nvisus/visuscpp/../visuscpp/kernel/core/visus_signalslot.h:258
#10	0x00000001001c1776 in Visus::Signal<Visus::Void>::emitSignal(Visus::Signal<Visus::Void>*, Visus::Void, Visus::Object*) at /Users/cam/code/nvisus/visuscpp/../visuscpp/kernel/core/visus_signalslot.h:147
#11	0x00000001001b0d3d in Visus::Signal<Visus::Void>::emitSignal(Visus::Void, Visus::Object*) at /Users/cam/code/nvisus/visuscpp/../visuscpp/kernel/core/visus_signalslot.h:100
#12	0x00000001006cbfae in Visus::Timer::onTimer() at /Users/cam/code/nvisus/visuscpp/../visuscpp/gui/visus_timer.h:52
#13	0x00000001006cc113 in Visus::Timer::Pimpl::timerCallback() at /Users/cam/code/nvisus/visuscpp/gui/visus_timer.cpp:60
#14	0x000000010100d5c1 in juce::Timer::TimerThread::callTimers() at /Users/cam/code/nvisus/libs/JUCE/modules/juce_events/timers/juce_Timer.cpp:127
#15	0x000000010100e9c7 in juce::Timer::TimerThread::CallTimersMessage::messageCallback() at /Users/cam/code/nvisus/libs/JUCE/modules/juce_events/timers/juce_Timer.cpp:198
#16	0x000000010100b427 in juce::MessageQueue::deliverNextMessage() at /Users/cam/code/nvisus/libs/JUCE/modules/juce_events/native/juce_osx_MessageQueue.h:79
#17	0x000000010100b31a in juce::MessageQueue::runLoopCallback() at /Users/cam/code/nvisus/libs/JUCE/modules/juce_events/native/juce_osx_MessageQueue.h:90
#18	0x000000010100b2d5 in juce::MessageQueue::runLoopSourceCallback(void*) at /Users/cam/code/nvisus/libs/JUCE/modules/juce_events/native/juce_osx_MessageQueue.h:99

**Comment by scrgiorgio** [comment]
Fixed https://github.com/sci-visus/nvisusio/commit/49ccb35a6ad0faa651a7c94b204228af110b28bf
