### ISSUE TITLE
maximatree modification should not require force refresh

### ISSUE THREAD

**Issue by cchriste** [sci-visus/visus-issues#232]
When modifying the values of a maxima tree (range, persistence, reduce min/max, etc), the user should not have to force a refresh to see the updated computation.

**Comment by scrgiorgio** [comment]
![image](https://cloud.githubusercontent.com/assets/1260735/6224533/8953bc74-b67d-11e4-9ebe-5696813738e5.png)

I know , this is a big problem of Visus.
 
The query extractor just publish to the "outside" (potentially to multiple nodes!)... how can the "Build Max Tree"-node force the query to republish?
See attached image.

**Comment by cchriste** [comment]
This should not require new data from the QueryNode. What changes are simply the parameters of the BuildJTreeNode, so it should re-use the existing data from the QueryNode and re-publish its own results.

Perhaps the BuildJTreeNode is not holding a pointer to its data? If not, then it will have to hold it!

**Comment by cchriste** [comment]
It turns out the BuildJTreeNode already held onto the input data. Therefore it was simple to make it recompute when its own settings were changed.

https://github.com/sci-visus/nvisusio/pull/336 contains fixes that recalculate the merge tree when its settings change. 

This works even though there are still a couple smaller issues. I'll resolve this bug once the change is merged and create separate issues for these items.
