### ISSUE TITLE
maxima tree: color by component shows all black

### ISSUE THREAD

**Issue by cchriste** [sci-visus/visus-issues#234]
When selecting color by component on the maxima tree, all the spheres are drawn in black. 

![screenshot 2015-02-10 12 06 25](https://cloud.githubusercontent.com/assets/1260945/6124336/a8e82ecc-b11d-11e4-8c9b-c202c2bf6509.png)

**Comment by scrgiorgio** [comment]
Fixed https://github.com/sci-visus/nvisusio/commit/8e793633948362b228ed172f343c13fd6c04e72b
