### ISSUE TITLE
visusconvert adding full path to filename_template

### ISSUE THREAD

**Issue by cchriste** [sci-visus/visus-issues#236]
This bug was fixed before, but seems to have returned:

*Currently:*
(filename_template)
/Users/cam/code/nvisus/docs/examples/visusconvert/./temp/googleearth/%02x.bin

*Should be:*
(filename_template)
./temp/googleearth/%02x.bin

**Comment by scrgiorgio** [comment]
Let's try again:

https://github.com/sci-visus/nvisusio/commit/15fdd99ca00a98a582f264f2c976e80653e08ddd
