### ISSUE TITLE
Visoar: Point of Interest Image scale and multiple point issues

### ISSUE THREAD

**Issue by amygooch** [sci-visus/visus-issues#237]
I looked into why Point of Interest Image scale slider in ViSAOR doesn't work and it only does work if the user puts down more than point for a point of interest.  As I remember Marek/EXXON hated the ability to add additional points.. and I have to agree

can we limit the Point of interest annotations to only  allow 1 point?  I can understand why Point of Interest Text may like having two to establish a bounding box... but for image, it only seems to confuse thing.  
for POI Text, I think it would be worth some user testing.

Amy

**Comment by scrgiorgio** [comment]
This issue was moved to sci-visus/nvisusio#509
