### ISSUE TITLE
ViSOAR: Select Annotation in the interior

### ISSUE THREAD

**Issue by amygooch** [sci-visus/visus-issues#238]
Currently, we only test for selecting an annotation by hitting the points that were added.

For POI Tex, POI Image, Polygon we should test for inside the polygon/object/etc.

Giorgio: if you can kind of brief me on this, I can probably implement it

Amy

**Comment by amygooch** [comment]
Giorgio: I can't get annotations to pick at all in the visusviewer and as I remarked in this issue, you can't select them in the center of the polygon.  If you pick them in the tree view, they don't display the vertex magnets.. and I think they should.. let me know if you have some time to chat about this over Skype or slack

**Comment by scrgiorgio** [comment]
This issue was moved to sci-visus/nvisusio#508
