### ISSUE TITLE
2D motion is jerky for large volumes

### ISSUE THREAD

**Issue by cchriste** [sci-visus/visus-issues#239]
For example, large OnDemand volumes (mandelbrot, checkerboard) or large google maps volumes.

Zooming deeply into these volumes eventually results in very jerky motion and parts of the boundary disappearing. For example, see the video showing the distortion using google maps.

(3.4mb 15s video)
https://www.dropbox.com/s/jzaoojx228fc8g3/distorted_zoom_small.mov?dl=0

**Comment by cchriste** [comment]
Here is a video of mandelbrot with the same problem (9.2mb):
https://www.dropbox.com/s/1j5g9xbslasddf0/distorted_zoom_mandelbrot.mov?dl=0

**Comment by cchriste** [comment]
Assigning to Valerio to get his thoughts on the issue.

**Comment by pascucci** [comment]
Interesting. It may be an indicator of a subtle bug regarding precision.......
How may levels in the hierarchy before you get the problem?

**Comment by cchriste** [comment]
This is a google maps or mandelbrot virtual dataset, so... many levels. It definitely seems to be related to floating point precision. It also seems related to issue #318.

**Comment by cchriste** [comment]
Just fyi, #318 is fixed but the jerkiness issues remains.

**Comment by scrgiorgio** [comment]
This issue was moved to sci-visus/nvisusio#507
