### ISSUE TITLE
Cannot compile with VISUS_BIGINT_BITS > 64

### ISSUE THREAD

**Issue by cchriste** [sci-visus/visus-issues#240]
There are a few errors, from ttmath's inability to interpret long long as a 64-bit value to several issues in LegacyDataset.

https://github.com/sci-visus/nvisusio/pull/336 will allow you to set NBITS during Cmake.

**Comment by scrgiorgio** [comment]
Can you try now: https://github.com/sci-visus/nvisusio/commit/cadba34f8a8bad87b729c46d38b508e2da422c71

It compiles (at least on windows)

**Comment by cchriste** [comment]
Still doesn't build. Buildbot interface supports selection of NBITS so it can easily be tested:
http://atlanta.sci.utah.edu:8010/builders/visus-osx-juce/builds/1622/steps/shell_1/logs/stdio

**Comment by scrgiorgio** [comment]
This issue was moved to sci-visus/nvisusio#506
