### ISSUE TITLE
recenter camera center of rotation does work when zoomed too close

### ISSUE THREAD

**Issue by cchriste** [sci-visus/visus-issues#241]
One can press 'x' to recenter the camera at a given point, but this only works when the user is zoomed far enough away from the volume. Otherwise, the intersection test at line 312 of visus_gllookatcamera.cpp fails:

      if (intersection.valid && intersection.tmin>0) 
        this->setCenterOfRotation(ray.getPoint(0.5*(intersection.tmin+intersection.tmax)));

This bug was probably introduced when the camera lf moved rather than simply modifying the fov to zoom.

**Comment by hoangthaiduong** [comment]
@cchriste do you mind changing those two lines to the following

```if (intersection.valid)
         this->setCenterOfRotation(ray.getPoint(0.5*std::max(intersection.tmin,0.0)+intersection.tmax)));```

and see if you get the desired behavior? Thanks.

**Comment by cchriste** [comment]
It's a little weird in that the camera position or fov seems to change, but the re-centering bug is fixed.
