### ISSUE TITLE
camera pan rate too slow

### ISSUE THREAD

**Issue by cchriste** [sci-visus/visus-issues#242]
Before the excellent changes to enable zooming close to the volume by moving the lf instead of changing the fov, the camera pan rate was "just right," with the object of the scene seeming to move along perfectly with the mouse.

Now it is too slow, and it feels like the user must drag and drag and drag to pan around the scene, especially when zoomed closer to the object. It's a real drag.

We love the new camera, but would like the old pan behavior.

**Comment by cchriste** [comment]
I'm happier with the updated pan rate. Closing this issue... for now. :)

**Comment by cchriste** [comment]
Sorry, I changed my mind after using this a lot today.

However, it seems at this point that the behavior is consistent whether close to the model or far, so all I want now is a way to tweak it. Can a configuration setting for pan rate be created? 

Basically, the behavior I want is for the model to appear to exactly follow the mouse, at any zoom level.

**Comment by cchriste** [comment]
It turns out according to @hoangthaiduong that the slow pan rate is intentional when the camera is inside the volume. There already existed multipliers for rotate and pan and these should be exposed via visus.config settings. Assigning to myself to do this (it's very easy) once I find a model that annoys me again (the microscopy volumes initially showed the issue, but I'm working mostly in climate now).

**Comment by scrgiorgio** [comment]
This issue was moved to sci-visus/nvisusio#505
