### ISSUE TITLE
minima tree actually creates maxima tree 

### ISSUE THREAD

**Issue by cchriste** [sci-visus/visus-issues#243]
Note changes in https://github.com/sci-visus/nvisusio/pull/336 that modify NeuroTrackerPlugin::pluginCreateMenu to set         action->minima_tree=true;

However, even correctly setting this property does not resolve the issue. The same problem is evident in both the CreateJTreeNode and the JTreeRenderNode.

**Comment by scrgiorgio** [comment]
Try now:

https://github.com/sci-visus/nvisusio/commit/f5f323ecdb341c154c0c0d2b9df9b1f5f6f0940d
