### ISSUE TITLE
min/max tree: full recompute unnecessary when changing reduce_minmax or min_persist

### ISSUE THREAD

**Issue by cchriste** [sci-visus/visus-issues#244]
See comment in BuildJTreeNode::onPropertyChange:

    //There used to be a way to do this without recomputing everything, but to do so we would
    //need to signal the job, with which we no longer have a connection. Is this by design?
    //For now, just include them above and do unnecessary recomputation. FIXME

**Comment by cchriste** [comment]
Giorgio, I am most interested in your comments on the philosophy of jobs disowned by their respective nodes and thoughts on how this issue might be resolved to facilitate more efficient node updates.

**Comment by scrgiorgio** [comment]
try now:

https://github.com/sci-visus/nvisusio/commit/47a7431de5ee2e4e153f0aeb643f7851c79e0b25
