### ISSUE TITLE
'compressed' no longer accepted by visusconvert

### ISSUE THREAD

**Issue by cchriste** [sci-visus/visus-issues#246]
Creating idx: works with 'default_compression(zip)' but not 'compressed' or 'compressed(zip)'.

does not work (creates idx with no compression):
visusconvert --create test_compressed.idx --box "0 1023 0 1023" --fields "data uint8[3] compressed(zip)"

**Comment by scrgiorgio** [comment]
Try now: https://github.com/sci-visus/nvisusio/commit/efc47037f3cece78011e2b7f650c1444bb968153
