### ISSUE TITLE
z08.idx is not a valid idx filename

### ISSUE THREAD

**Issue by cchriste** [sci-visus/visus-issues#247]
I stumbled on this issue tonight and spend a good hour just trying to figure it out: these two idx files are identical. They even refer to the same data location. The one named z08.idx shows absolutely nothing in the viewer, while the other one works fine!

Try it here (1.5mb):
https://www.dropbox.com/s/h2z26x54e8dxsgy/Archive.zip?dl=0

**Comment by cchriste** [comment]
Note: even Z08.idx works, while z08.idx does not.

**Comment by scrgiorgio** [comment]
Hi cameron,

tried and they both work fine.
i.e. I can see a little picture (about 1% of the overall dataset) on the bottom-left.
Could be an issue of 'chmod' for the idx?
Anyway try to debug it:

  <Configuration>
       
    <IdxDiskAccess  **verbose="1"** nthreads="3" />
    <IdxFile        **verbose="1"** />
   ...

and let me know (or send me the logs)

**Comment by cchriste** [comment]
This is really a duplicate of #248. There was never a problem with the name z08 (whew!).
