### ISSUE TITLE
visusconvert does not accept full paths to --export idx

### ISSUE THREAD

**Issue by cchriste** [sci-visus/visus-issues#248]
(note differences in visusconvert output below)

**works:**
visusconvert --import ~/Dropbox/Photos/pui.jpg --export ./Z08.idx --box "0 719 0 959" --use-write-lock

**does not work:**
visusconvert --import ~/Dropbox/Photos/pui.jpg --export  /Users/cam/visus/cached_files/googleearth/Z08.idx --box "0 719 0 959" --use-write-lock

**misc info**
mercury:googleearth cam$ pwd
/Users/cam/visus/cached_files/googleearth
mercury:googleearth cam$ ls -al 
total 32
drwxr-xr-x+  7 cam  sci   238B Mar  2 00:24 ./
drwxr-xr-x+ 50 cam  sci   1.7K Mar  1 13:35 ../
drwxr-xr-x+ 17 cam  sci   578B Mar  2 00:27 Z08/
-rw-r--r--+  1 cam  sci   276B Mar  2 00:13 Z08.idx
mercury:googleearth cam$ which visusconvert
/Users/cam/code/nvisus/build/develop/Release/visusconvert.app/Contents/MacOS/visusconvert

**output (works):**
00:27:01.6812 INFO APPLICATION.369 Writing log messages to /Users/cam/visus/visus.log
00:27:01.6816 INFO APPLICATION.372 
****************************************************
** ViSUS Visualization Project                    **
** Copyright (c) 2010 University of Utah          **
** Scientific Computing and Imaging Institute     **
** 72 S Central Campus Drive, Room 3750           **
** Salt Lake City, UT 84112                       **
**                                                **
** For information about this project see:        **
** http://www.pascucci.org/visus/                 **
**                                                **
**      or contact: pascucci@sci.utah.edu         **
**                                                **
****************************************************

00:27:01.6817 INFO APPLICATION.373 osx64-release-6d8df1dc11bf7f9b6103c0d88cdb9646a07ef8b7
00:27:01.6817 INFO APPLICATION.375 Log file /Users/cam/visus/visus.log (ok)
00:27:01.6817 INFO APPLICATION.377 $(VisusUserDirectory)             /Users/cam/visus
00:27:01.6817 INFO APPLICATION.378 $(VisusCacheDirectory)            /Users/cam/visus/cached_files
00:27:01.6817 INFO APPLICATION.379 $(CurrentApplicationFile)         
00:27:01.6817 INFO APPLICATION.380 $(CurrentWorkingDirectory)        /Users/cam/visus/cached_files/googleearth
00:27:01.6817 INFO APPLICATION.381 $(ResourcesDirectory)             /Users/cam/code/nvisus/build/develop/Release/visusconvert.app/Contents
00:27:01.6818 INFO APPLICATION.401 Trying to use current working directory(/Users/cam/visus/cached_files/googleearth/visus.config) exists(NO)
00:27:01.6818 INFO APPLICATION.409 Trying to use visus data directory (/Users/cam/visus/visus.config) exists(YES)
00:27:01.6841 INFO APPLICATION.476 Found Visus configuration [/Users/cam/visus/visus.config]
00:27:01.6842 INFO APPLICATION.498 Configuration/Application/DefaultNetPool/nconnections=64
00:27:01.6843 INFO CPPMODULE.54 initialising module IdxModule
00:27:01.6843 INFO CPPMODULE.54 initialising module DBModule
00:27:01.6843 INFO CPPMODULE.54 initialising module DataflowModule
00:27:01.6843 INFO CPPMODULE.54 initialising module KernelModule
00:27:01.6845 INFO VISUSCONVERT.769 
00:27:01.6845 INFO VISUSCONVERT.770 [--import] Got in input dtype(uint8) dims(0 0 0 0 0)
00:27:01.7056 INFO ARRAY_PLUGIN.FREEIMAGE.182 FreeImageToArray(/Users/cam/Dropbox/Photos/pui.jpg) done (dtype=uint8[3]) FREE_IMAGE_TYPE(FIT_BITMAP/24) in 1msec
00:27:01.7056 INFO VISUSCONVERT.769 
00:27:01.7056 INFO VISUSCONVERT.770 [--export] Got in input dtype(uint8[3]) dims(720 960 1 1 1)
00:27:01.7082 INFO IDX_BOXQUERY.139 IdxBoxQuery cache built for the first time in 2 msec memsize=920.0kb
00:27:01.8279 INFO DB_ARRAYPLUGIN.298 field(data) original-size(2.0mb) bytes_read(4.9mb) bytes_write(4.9mb)
00:27:01.8279 INFO DB_ARRAYPLUGIN.304 DatasetArrayPlugin::handleSaveImage(./Z08.idx,..) done in 0.119 seconds

**output (does not work):**
00:26:45.7324 INFO APPLICATION.369 Writing log messages to /Users/cam/visus/visus.log
00:26:45.7328 INFO APPLICATION.372 
****************************************************
** ViSUS Visualization Project                    **
** Copyright (c) 2010 University of Utah          **
** Scientific Computing and Imaging Institute     **
** 72 S Central Campus Drive, Room 3750           **
** Salt Lake City, UT 84112                       **
**                                                **
** For information about this project see:        **
** http://www.pascucci.org/visus/                 **
**                                                **
**      or contact: pascucci@sci.utah.edu         **
**                                                **
****************************************************

00:26:45.7329 INFO APPLICATION.373 osx64-release-6d8df1dc11bf7f9b6103c0d88cdb9646a07ef8b7
00:26:45.7329 INFO APPLICATION.375 Log file /Users/cam/visus/visus.log (ok)
00:26:45.7329 INFO APPLICATION.377 $(VisusUserDirectory)             /Users/cam/visus
00:26:45.7329 INFO APPLICATION.378 $(VisusCacheDirectory)            /Users/cam/visus/cached_files
00:26:45.7329 INFO APPLICATION.379 $(CurrentApplicationFile)         
00:26:45.7329 INFO APPLICATION.380 $(CurrentWorkingDirectory)        /Users/cam/visus/cached_files/googleearth
00:26:45.7329 INFO APPLICATION.381 $(ResourcesDirectory)             /Users/cam/code/nvisus/build/develop/Release/visusconvert.app/Contents
00:26:45.7329 INFO APPLICATION.401 Trying to use current working directory(/Users/cam/visus/cached_files/googleearth/visus.config) exists(NO)
00:26:45.7330 INFO APPLICATION.409 Trying to use visus data directory (/Users/cam/visus/visus.config) exists(YES)
00:26:45.7352 INFO APPLICATION.476 Found Visus configuration [/Users/cam/visus/visus.config]
00:26:45.7353 INFO APPLICATION.498 Configuration/Application/DefaultNetPool/nconnections=64
00:26:45.7354 INFO CPPMODULE.54 initialising module IdxModule
00:26:45.7354 INFO CPPMODULE.54 initialising module DBModule
00:26:45.7354 INFO CPPMODULE.54 initialising module DataflowModule
00:26:45.7354 INFO CPPMODULE.54 initialising module KernelModule
00:26:45.7356 INFO VISUSCONVERT.769 
00:26:45.7356 INFO VISUSCONVERT.770 [--import] Got in input dtype(uint8) dims(0 0 0 0 0)
00:26:45.7560 INFO ARRAY_PLUGIN.FREEIMAGE.182 FreeImageToArray(/Users/cam/Dropbox/Photos/pui.jpg) done (dtype=uint8[3]) FREE_IMAGE_TYPE(FIT_BITMAP/24) in 2msec
00:26:45.7560 INFO VISUSCONVERT.769 
00:26:45.7560 INFO VISUSCONVERT.770 [--export] Got in input dtype(uint8[3]) dims(720 960 1 1 1)
00:26:45.7585 INFO IDX_BOXQUERY.139 IdxBoxQuery cache built for the first time in 2 msec memsize=920.0kb
00:26:45.7609 INFO IDX_BOXQUERY.139 IdxBoxQuery cache built for the first time in 2 msec memsize=920.0kb
00:26:45.7628 INFO IDX_BOXQUERY.139 IdxBoxQuery cache built for the first time in 1 msec memsize=920.0kb
00:26:45.7630 WARNING DB_ARRAYPLUGIN.294 dataset->executeBoxQuery(dataset,Q)!="QueryOk"
00:26:45.7630 INFO APPLICATION.707 Cannot saveImage(/Users/cam/visus/cached_files/googleearth/Z08.idx)

**Comment by cchriste** [comment]
This seems to be getting hung up on an inappropriate access config found in the visus.config.

In DatasetArrayPlugin::handleSaveImage, an access is created from the dataset, and in IdxDataset::createAccess the access_configs are read using getAccessConfigs, which looks for the first non-empty access in the visus.config. This happens to be a 3-level multiplex, which is why we see three "cache built" messages instead of only one: it's actually opening three .idx fies!

The actual failure occurs when it gets into the guts of IdxDataset::IdxExecuteBoxQuery::executeWrite and apparently tries to acquire a lease, which isn't permitted for box queries.

As to the case that works, when specifying the file as a relative path to the current directory, the call to getAccessConfigs from IdxDataset::createAccess returns nothing! The url is then determined to be a file and a default normal IdxDiskAccess is created. So it appears the damage is already done when the IdxDataset is created in the first place.

Stay tuned...

**Comment by cchriste** [comment]
It appears this function eagerly discovers an entry that references the specified dataset in the visus.config file (in the second "try to find in url..." part). 

For some reason the config it finds is inappropriate for the given action (perhaps because the first level of the mutiplex is read-only). But maybe there is a bigger problem with this. For example, what if I have multiple entries in my visus.config that reference the same dataset, which is common for me right now? It will always pick the first. 

Probably there is some important functionality that requires looking at visus.config for dataset access, but I wonder if it should be restricted only to the name and not to the url.

  static StringTree* findDatasetConfig(String name)
  {
    std::vector<StringTree*> configs=Application::getCurrent()->getConfig()->findAllChildsWithName("dataset",/*bRecursive*/true);

    //first try with the name
    for (int i=0;i<(int)configs.size();i++) 
    {
      if (configs[i]->readString("name")==name) 
        return configs[i];
    }

    //try to find in url ....
    for (int i=0;i<(int)configs.size();i++) 
    {
      String config_url=configs[i]->readString("url");
      if (config_url==name || config_url==("file://"+name)) 
        return configs[i];
    }

    return nullptr;
  }

**Comment by cchriste** [comment]
Commenting out the "try to find url..." section resolves my issues of using a config entry when that is not desired. 

I'm not sure when this functionality would be appropriate and unless there is a compelling reason to maintain it, I propose removing the "try to find url..." section.

**Comment by scrgiorgio** [comment]
thanks for providing so detailed infos.
So  are you suggesting to use a dataset/config only the dataset  has a "name="?
I'm fine with that....But not sure about others visus.config (read Amy,Valerio)?

Example. visus.config:

<dataset url="http:/....">
   blah blah blah
</dataset>

I think that I'm doing somewhere else (so I need to track down where it happens):

   url=config.read("url");
   name=config.read("name",/*default_if_name_not_found*/url);

Let me know.

**Comment by amygooch** [comment]
It seems like Mike or I put that in there to solve issues on the iPad....

I can try to test it...
Amy


On Fri, Mar 6, 2015 at 12:42 AM, scrgiorgio <notifications@github.com>
wrote:

> thanks for providing so detailed infos.
> So are you suggesting to use a dataset/config only the dataset has a
> "name="?
> I'm fine with that....But not sure about others visus.config (read
> Amy,Valerio)?
>
> Example. visus.config:
>
>
> blah blah blah
>
> I think that I'm doing somewhere else (so I need to track down where it
> happens):
>
> url=config.read("url");
> name=config.read("name",/*default_if_name_not_found*/url);
>
> Let me know.
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/sci-visus/visus-issues/issues/248#issuecomment-77514407>
> .
>



-- 
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
"Tell me and I'll forget; show me and I may remember; involve me and I'll
understand."
Chinese Proverb


~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Dr. Amy Ashurst Gooch          http://www.sci.utah.edu/people/agooch.html
<http://www.csc.uvic.ca/~agooch>
Research Scientist                                          amy.a.gooch at
gmail.com
Scientific Computing and Imaging                          agooch at
sci.utah.edu
University of Utah

979 353 1230    (Texas Virtual)
801 828 5038    (Cell)
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

**Comment by cchriste** [comment]
Hi Amy,
If you consider the pain this non-obvious feature is causing, not to mention the potential problems when there are more than one configuration for a given url, it seems worth trying to find a better workaround for whatever bug it might have been addressing.
Kindly,
Cameron

**Comment by amygooch** [comment]
I'm sorry for the bug.  I'm not owning up to it yet (I'm  not sure I put it
there), and  I still need to understand it...

But by all means, take it out of the branch for now.. I'll figure out if it
has to be there as and IOS specific thing.
At the very least, we can put the #if VISUS_IOS around it. or a #if 0  and
mark it Cameron's thorn.

Amy




On Sat, Mar 7, 2015 at 10:13 AM, Cameron Christensen <
notifications@github.com> wrote:

> Hi Amy,
> If you consider the pain this non-obvious feature is causing, not to
> mention the potential problems when there are more than one configuration
> for a given url, it seems worth trying to find a better workaround for
> whatever bug it might have been addressing.
> Kindly,
> Cameron
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/sci-visus/visus-issues/issues/248#issuecomment-77695790>
> .
>



-- 
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
"Tell me and I'll forget; show me and I may remember; involve me and I'll
understand."
Chinese Proverb


~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Dr. Amy Ashurst Gooch          http://www.sci.utah.edu/people/agooch.html
<http://www.csc.uvic.ca/~agooch>
Research Scientist                                          amy.a.gooch at
gmail.com
Scientific Computing and Imaging                          agooch at
sci.utah.edu
University of Utah

979 353 1230    (Texas Virtual)
801 828 5038    (Cell)
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

**Comment by cchriste** [comment]
I took out the "try to find in url" section. It only gets in the way. If we want "automatic" caching we should consider a different tactic. I'll submit a pull request.
