### ISSUE TITLE
part of manipulator clipped from view when zooming in

### ISSUE THREAD

**Issue by cchriste** [sci-visus/visus-issues#249]
This happend when you zoom in and rotate. Part of the manipulator disappears.

Load a volume such as http://atlantis.sci.utah.edu/mod_visus?dataset=3Scan_block1
(it may have something to do with anisotropic, so try this one if you don't see it in 2kbit1)

![screenshot 2015-03-03 21 18 18](https://cloud.githubusercontent.com/assets/1260945/6469148/1da055fe-c1eb-11e4-9ef1-b2cff003c5fb.png)

**Comment by cchriste** [comment]
This is definitely still an issue, and may be related to #365

**Comment by scrgiorgio** [comment]
This issue was moved to sci-visus/nvisusio#503
