### ISSUE TITLE
2d slices should support partial transparency

### ISSUE THREAD

**Issue by cchriste** [sci-visus/visus-issues#250]
Currently 2d slices only support transparency when they are completely transparent. Notice in these screenshots how each partially transparent slice inappropriately occludes some of its peers. 

![screenshot 2015-03-03 21 51 59](https://cloud.githubusercontent.com/assets/1260945/6469701/a652b190-c1ef-11e4-87a5-cb06758b07e3.png)
![screenshot 2015-03-03 21 51 57](https://cloud.githubusercontent.com/assets/1260945/6469702/a670d13e-c1ef-11e4-8517-9131a7689626.png)
![screenshot 2015-03-03 21 51 51](https://cloud.githubusercontent.com/assets/1260945/6469704/a677969a-c1ef-11e4-92e8-8c1a33b0eff2.png)
![screenshot 2015-03-03 21 51 49](https://cloud.githubusercontent.com/assets/1260945/6469703/a676c44a-c1ef-11e4-95a3-02b32904836c.png)
![screenshot 2015-03-03 21 51 42](https://cloud.githubusercontent.com/assets/1260945/6469705/a677bac6-c1ef-11e4-85db-c55a3e09bd8a.png)
![screenshot 2015-03-03 21 51 36](https://cloud.githubusercontent.com/assets/1260945/6469706/a6789efa-c1ef-11e4-8cd6-06d949190dc4.png)

**Comment by scrgiorgio** [comment]
This issue was moved to sci-visus/nvisusio#502
