### ISSUE TITLE
MeshRenderNode frees mesh data that is potentially needed later by another node

### ISSUE THREAD

**Issue by cchriste** [sci-visus/visus-issues#254]
Problem:

Currently in ViSUS, if I add an IsoContourNode, it automatically creates a MarchingCube node which creates a triangle mesh and forward this mesh to a MeshRenderNode.MeshRenderNode uploads the data to the GPU and deallocates the data on CPU's memory. However, this mesh data could be needed by some other node which also takes input from MarchingCube, such as the one I'm currently writing called IsoNormalIntegrationNode. By the time the user right clicks on MarchingCube and adds an IsoNormalIntegrationNode, the mesh created by MarchingCube has already been rendered and its data is gone from RAM.

Possible solutions:

1) Don't deallocate data after it is uploaded to the GPU. The issue is that the deallocation happens in the GLArrayBuffer class, and from the point of view of this class, it makes sense to deallocate the data since it doesn't (and should not) know about the dataflow. Also, we would waste some memory by not freeing the mesh.

2) Automatically create the IsoNormalIntegrationNode at the time of creation of IsoContourNode, and "intercept" the link between MarchingCube and MeshRenderNode. This is inelegant since IsoNormalIntegrationNode is not something that everyone who wants an iso-contour care about, and it is awkward to enable it by default. Also, we haven't solved the issue of memory waste.

3) Don't automatically enable the MeshRenderNode when creating an iso-contour (i.e., don't render the mesh immediately), instead let the user choose if he wants to render the surface by either enabling the MeshRenderNode, or clicking some button.

4) Proposed by Giorgio: don't store the mesh data in GLMesh but in an Array, and convert it to GLMesh only at MeshRenderNode. I'm not quite sure how this can help (Giorgio, please help explain this solution if you can). Also, storing a mesh in a simple Array is not the best idea, as all the topological information is lost.

Bigger picture:

I think this issue illustrates another bigger problem with the current dataflow design: it is hard to dynamically update the flow. Maybe the solution is to delay the execution of the dataflow until the user clicks a "Go" button or something (see point 3) above). This will limit interactivity a bit but will makes handling dynamic dataflow much easier. This is also the approach taken by ParaView.

**Comment by cchriste** [comment]
Hi Duong,

Thanks for bringing up this important topic.

Overall, perhaps dataflow nodes should hang on to their own outputs until they are replaced or the node itself is removed. In this way the system is like a live circuit where outputs remain "hot" and always available to potential inputs. 

In the case of the mesh renderer, it can release a shared ptr that it no longer needs, but the pointer will remain alive until the upstream dataflow node itself replaces it for some reason.

Alternatively, for items like the mesh output of the marching cubes node, if a new input is connected to an output that has been released, the node should simply recompute it. This implies that at least a reference to the original input data is held.

Looking to the next possible level where portions of the dataflow can be exported to different resources, simple shared ptrs will not be sufficient and a more explicit means of ensuring data stays alive ("hot") long enough will be necessary. This notion might lead us to the key to a ubiquitous caching scheme suitable for utilization of disparate computational resources.

Regards,
Cameron

P.S.
I do not agree this is merely an issue of timing. For example, the solution proposed in #3 would exhibit the same symptom if the user first created the render node then (tried to) create the analysis node. Nor do I believe this is a one-off case where switching output data types would resolve the issue throughout the system, as proposed in #4.

Maintaining an interactive dataflow should remain paramount in our design precisely so we do not end up with the unpleasantly stertorous interaction style of visit and paraview, which both have attempted to mitigate through their respective and buggy "auto apply" modes.

**Comment by hoangthaiduong** [comment]
Closing. The solution taken in current "develop" is 1) Don't deallocate data after it is uploaded to the GPU.
