### ISSUE TITLE
add ability to "update" a subregion of a filtered dataset

### ISSUE THREAD

**Issue by cchriste** [sci-visus/visus-issues#255]
> I would like to apply a filter to a subregion of the image, since the image is massive. 

> Use case: a portion of a dataset with filter is updated with new content. The filter must be re-applied to a subset of that dataset that contains the updated content. Re-applying the filter to the entire dataset is too time-consuming (consider terapixel imagery with a max filter). 

From Giorgio:
Consider when I add some data: I know where the data is located in the image. Is it correct that in theory one could re-apply the filter only in this subregion (or power of 2 region that encompasses it).

Just to correct what I said in my previous email: the filter must be applied bottom-up.

For simplicity let's assume that the filter size is 2 (but we can handle something diffent) to have a proper alighment to the 2^n overall bonding box.

(See the query-filter-explanation.gif in github)
The bitmask is V0101, the levels will be in the range [0,4] 
Say we need to modify the top-right subregion:

   [2,4)x[2,4)

then we need to recompute the filters:

  1 Level 4 -> only [2,4)x[2,4)
  0 Level 3 -> only [2,4)x[2,4]
  1 Level 2 -> all    [0,4]x[0,4]
  0 Level 1 -> all    [0,4]x[0,4]
  V Level 0 -> all    [0,4]x[0,4]

Maybe we can modify the filters to handle these particular cases, but won't be so easy (it's a long time I'm not touching that part of code).

I have experimented and created filtered versions of some images (just 2^8 square not 2^20!) using the max filter and the results are pleasing. But the time to apply the filter is significant.

Can you do some performance test? Is the time consumed in writing the data on the disk (i.e. I need to rewrite the data several times) or in the computation of the field (I except that part can be improved a little).

CIao,Giorgio.

**Comment by scrgiorgio** [comment]
This issue was moved to sci-visus/nvisusio#500
