### ISSUE TITLE
Palette window does not show the currently selected color scheme

### ISSUE THREAD

**Issue by hoangthaiduong** [sci-visus/visus-issues#257]
ViSUS version 11f1128287e04617792eb3156b2f075fc52e3072

If we select a color scheme and close the palette window, the selection is not shown anymore when the same palette window is opened later. See two screenshots below, the first one is the current behavior, the second one is the expected behavior.

![palette](https://cloud.githubusercontent.com/assets/8607075/6545174/e6f6c248-c589-11e4-9678-025b70d50be2.jpg)
![palette2](https://cloud.githubusercontent.com/assets/8607075/6545178/2caf7ac8-c58a-11e4-8c88-f049faf64f76.jpg)

**Comment by scrgiorgio** [comment]
Try again:
https://github.com/sci-visus/nvisusio/commit/eb011a0b8887677f7f9c6e3fd276dc21cb2d539f

**Comment by hoangthaiduong** [comment]
Yes the name of the color scheme is back but the check icon (the V symbol) in the drop down list is not there. It would be nice to have it there as well for consistency.

**Comment by scrgiorgio** [comment]
Try now:

https://github.com/sci-visus/nvisusio/commit/dc92009e5c38cfa9210db7700840c663b43c3a3b
