### ISSUE TITLE
add log scale to palette

### ISSUE THREAD

**Issue by cchriste** [sci-visus/visus-issues#259]
Often it seems we are trying to manipulate the palette curves down to just one pixel above zero and it's very difficult. 

Showing the curves using a log scale would help when data ranges are dramatic and intervals of interest are small.

I am just thinking of a vertical log scale, but using a horizontal log scale might also be interesting.

**Comment by scrgiorgio** [comment]
This issue was moved to sci-visus/nvisusio#499
