### ISSUE TITLE
add "attenuation" to palette

### ISSUE THREAD

**Issue by cchriste** [sci-visus/visus-issues#260]
It would be helpful for many datasets to add an additional transparency control above and beyond what can be expressed using the palette alone. Also, this would be even more useful for rgb datasets such as visible human where transparency is currently impossible.

VisIt has this feature and calls it "attenuation." It just adds a percentage slider to the palette dialog, and includes the additional alpha in the rendering computation.

**Comment by scrgiorgio** [comment]
See https://github.com/sci-visus/nvisusio/commit/84e8371bb9cff0e32cec555f17e52d6510ed2150

It will work only when (a) the transfer function is applied on GPU and (b) with 4 functions (RGBA). 

The attenuation will change the alpha channel in this way:

  alpha'=alpha*(1.0-attenuation);

Still todo:

(Cameron) Can you check if it's working for you?

(Amy) Need to add attenuation to experimental GUI layout. You need a new slider which is linked to TransferFunction::{getAttenuation|setAttenuation}

**Comment by amygooch** [comment]
Added GUI element .. will get pull request soon

**Comment by cchriste** [comment]
Btw, I long ago confirmed this is working, and it's very useful.
I'll close this bug.
