### ISSUE TITLE
continue to display last successfully loaded data when out of memory

### ISSUE THREAD

**Issue by cchriste** [sci-visus/visus-issues#261]
Currently, when a ram resource shortage is detected, the currently rendered resolution level is cleared but no data replaces it

This is very disconcerting to the user.

An out of memory condition should be detected prior to clearing the current render. This aligns with our commitment to operate on systems with varying resources.

It's easy to reproduce this situation using the quality slider if it doesn't happen on it's own.

The screenshots show what the render of lifted_flame (on atlantis) looks like just prior to the out-of-memory indication, and just afterwards, along with the corresponding log.

![screenshot 2015-03-08 23 45 48](https://cloud.githubusercontent.com/assets/1260945/6547619/0f96abaa-c5ee-11e4-9f5c-cbf4f9ed236d.png)
![screenshot 2015-03-08 23 45 24](https://cloud.githubusercontent.com/assets/1260945/6547621/1510d0f6-c5ee-11e4-93d4-80b31d754933.png)
![screenshot 2015-03-08 23 45 58](https://cloud.githubusercontent.com/assets/1260945/6547622/19b078fa-c5ee-11e4-92db-0388f7a80099.png)

**Comment by scrgiorgio** [comment]
I think I need a movie to understand how to fix it...

**Comment by cchriste** [comment]
Some more information...

This is a crazy problem seems with OSX OpenGL, in which the upload seems to complete successfully (or at least I see no error in the visus log), but the GPU ends up empty and the rendering disappears.

It seems the RamResource out of memory error is simply coincidental.

**Comment by cchriste** [comment]
I'm assigning this to Aniketh since we talked about the details of the issue yesterday in relation to the Angelucci data, as well as a potential solution.

**Comment by scrgiorgio** [comment]
This issue was moved to sci-visus/nvisusio#498
