### ISSUE TITLE
Gigapixel David not working for many users

### ISSUE THREAD

**Issue by cchriste** [sci-visus/visus-issues#264]
The iOS app just hangs for many users (Valerio's iPhone 5S is the only one that worked out of three devices, and I think he was using the latest iOS 8.1.3). David Keyes iPhone 4 (not sure which iOS version) hangs. My iPhone 5 (not S) (also iOS 8.1.3) hangs. 

I investigated a bit using my phone:
- device logs have nothing from this app. 
- in davidapp.cpp, verified the dataset url is http://atlantis.sci.utah.edu/mod_visus?dataset=david.
- visus.log on atlantis and there are indeed requests being made to the server, as seen below.

And... eventually (after about two minutes), something is finally displayed in the app. I was able to zoom in and then wait for basically another eternity (five more minutes) before just part of that image was updated, and even after fifteen minutes the portion I zoomed (the head) was still not resolved.

*During this time the app is completely unresponsive. The user cannot change views or interact with the canvas.*

**My suspicion:** the "progression" is causing data that gets sent to be ignored until more data is received, at least the first 7 blocks (as indicated by the log). When this takes two minutes the average user just thinks the app has hung and moves on. The unresponsiveness could be caused by not using threads for the network transfer, so a delayed transfer is causing the entire app to hang.

**Suggested solution:** include the first 7 blocks with the app, increase the progression to display data more frequently, provide an indication of ongoing data transfer, and figure out why the app is unresponsive when the server is slow.

Here is the log from atlantis of the first two minutes of running the app:
01:29:03.6325 INFO DB_MODVISUS.603 Got new request http://localhost/mod_visus?action=readdataset&dataset=david
01:29:04.5444 INFO DB_MODVISUS.603 Got new request http://localhost/mod_visus?action=readdataset&dataset=david
01:29:05.9473 INFO DB_MODVISUS.603 Got new request http://localhost/mod_visus?action=rangequery&compression=zip&dataset=david&field=data&from=0&time=0&to=65536
01:29:05.9508 INFO DB_MODVISUS.603 Got new request http://localhost/mod_visus?action=rangequery&compression=zip&dataset=david&field=data&from=65536&time=0&to=131072
01:31:07.6348 INFO DB_MODVISUS.603 Got new request http://localhost/mod_visus?action=rangequery&compression=zip&dataset=david&field=data&from=393216&time=0&to=458752
01:31:07.6358 INFO DB_MODVISUS.603 Got new request http://localhost/mod_visus?action=rangequery&compression=zip&dataset=david&field=data&from=196608&time=0&to=262144
01:31:07.6378 INFO DB_MODVISUS.603 Got new request http://localhost/mod_visus?action=rangequery&compression=zip&dataset=david&field=data&from=131072&time=0&to=196608
01:31:07.6383 INFO DB_MODVISUS.603 Got new request http://localhost/mod_visus?action=rangequery&compression=zip&dataset=david&field=data&from=262144&time=0&to=327680
01:31:07.6384 INFO DB_MODVISUS.603 Got new request http://localhost/mod_visus?action=rangequery&compression=zip&dataset=david&field=data&from=327680&time=0&to=393216

**Comment by amygooch** [comment]
acknowledged.. I'll look into it and will need someone to help me with
getting the first 7 blocks of data to include with the app

Amy

On Tue, Mar 10, 2015 at 2:45 AM, Cameron Christensen <
notifications@github.com> wrote:

> The iOS app just hangs for many users (Valerio's iPhone 5S is the only one
> that worked out of three devices, and I think he was using the latest iOS
> 8.1.3). David Keyes iPhone 4 (not sure which iOS version) hangs. My iPhone
> 5 (not S) (also iOS 8.1.3) hangs.
>
> I investigated a bit using my phone:
>
>    - device logs have nothing from this app.
>    - in davidapp.cpp, verified the dataset url is
>    http://atlantis.sci.utah.edu/mod_visus?dataset=david.
>    - visus.log on atlantis and there are indeed requests being made to
>    the server, as seen below.
>
> And... eventually (after about two minutes), something is finally
> displayed in the app. I was able to zoom in and then wait for basically
> another eternity (five more minutes) before just part of that image was
> updated, and even after fifteen minutes the portion I zoomed (the head) was
> still not resolved.
>
> *During this time the app is completely unresponsive. The user cannot
> change views or interact with the canvas.*
>
> *My suspicion:* the "progression" is causing data that gets sent to be
> ignored until more data is received, at least the first 7 blocks (as
> indicated by the log). When this takes two minutes the average user just
> thinks the app has hung and moves on. The unresponsiveness could be caused
> by not using threads for the network transfer, so a delayed transfer is
> causing the entire app to hang.
>
> *Suggested solution:* include the first 7 blocks with the app, increase
> the progression to display data more frequently, provide an indication of
> ongoing data transfer, and figure out why the app is unresponsive when the
> server is slow.
>
> Here is the log from atlantis of the first two minutes of running the app:
> 01:29:03.6325 INFO DB_MODVISUS.603 Got new request
> http://localhost/mod_visus?action=readdataset&dataset=david
> 01:29:04.5444 INFO DB_MODVISUS.603 Got new request
> http://localhost/mod_visus?action=readdataset&dataset=david
> 01:29:05.9473 INFO DB_MODVISUS.603 Got new request
> http://localhost/mod_visus?action=rangequery&compression=zip&dataset=david&field=data&from=0&time=0&to=65536
> 01:29:05.9508 INFO DB_MODVISUS.603 Got new request
> http://localhost/mod_visus?action=rangequery&compression=zip&dataset=david&field=data&from=65536&time=0&to=131072
> 01:31:07.6348 INFO DB_MODVISUS.603 Got new request
> http://localhost/mod_visus?action=rangequery&compression=zip&dataset=david&field=data&from=393216&time=0&to=458752
> 01:31:07.6358 INFO DB_MODVISUS.603 Got new request
> http://localhost/mod_visus?action=rangequery&compression=zip&dataset=david&field=data&from=196608&time=0&to=262144
> 01:31:07.6378 INFO DB_MODVISUS.603 Got new request
> http://localhost/mod_visus?action=rangequery&compression=zip&dataset=david&field=data&from=131072&time=0&to=196608
> 01:31:07.6383 INFO DB_MODVISUS.603 Got new request
> http://localhost/mod_visus?action=rangequery&compression=zip&dataset=david&field=data&from=262144&time=0&to=327680
> 01:31:07.6384 INFO DB_MODVISUS.603 Got new request
> http://localhost/mod_visus?action=rangequery&compression=zip&dataset=david&field=data&from=327680&time=0&to=393216
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/sci-visus/visus-issues/issues/264>.
>



-- 
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
"Tell me and I'll forget; show me and I may remember; involve me and I'll
understand."
Chinese Proverb


~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Dr. Amy Ashurst Gooch          http://www.sci.utah.edu/people/agooch.html
<http://www.csc.uvic.ca/~agooch>
Research Scientist                                          amy.a.gooch at
gmail.com
Scientific Computing and Imaging                          agooch at
sci.utah.edu
University of Utah

979 353 1230    (Texas Virtual)
801 828 5038    (Cell)
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

**Comment by scrgiorgio** [comment]
This issue was moved to sci-visus/nvisusio#497
