### ISSUE TITLE
time slider needs indication of current time step

### ISSUE THREAD

**Issue by cchriste** [sci-visus/visus-issues#266]
I really like the latest time slider with the play button. 

The only improvement necessary is that the user needs to be able to see the current time step without moving the slider.

**Comment by amygooch** [comment]
yeah, I was playing with where to put it.. I'm on it.. I'll figure it out

On Wed, Mar 11, 2015 at 4:47 AM, Cameron Christensen <
notifications@github.com> wrote:

> I really like the latest time slider with the play button.
>
> The only improvement necessary is that the user needs to be able to see
> the current time step without moving the slider.
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/sci-visus/visus-issues/issues/266>.
>



-- 
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
"Tell me and I'll forget; show me and I may remember; involve me and I'll
understand."
Chinese Proverb


~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Dr. Amy Ashurst Gooch          http://www.sci.utah.edu/people/agooch.html
<http://www.csc.uvic.ca/~agooch>
Research Scientist                                          amy.a.gooch at
gmail.com
Scientific Computing and Imaging                          agooch at
sci.utah.edu
University of Utah

979 353 1230    (Texas Virtual)
801 828 5038    (Cell)
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

**Comment by cchriste** [comment]
like

**Comment by amygooch** [comment]
fixed:
@Giorgio: please consider:

https://github.com/sci-visus/nvisusio/pull/346

(I'd like to use the popup bubble instead and enable it on.. but haven't
got it to work, so this will do in the meantime)

Amy


On Wed, Mar 11, 2015 at 7:48 AM, Cameron Christensen <
notifications@github.com> wrote:

> like
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/sci-visus/visus-issues/issues/266#issuecomment-78256268>
> .
>



-- 
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
"Tell me and I'll forget; show me and I may remember; involve me and I'll
understand."
Chinese Proverb


~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Dr. Amy Ashurst Gooch          http://www.sci.utah.edu/people/agooch.html
<http://www.csc.uvic.ca/~agooch>
Research Scientist                                          amy.a.gooch at
gmail.com
Scientific Computing and Imaging                          agooch at
sci.utah.edu
University of Utah

979 353 1230    (Texas Virtual)
801 828 5038    (Cell)
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

**Comment by cchriste** [comment]
Not sure why this is assigned back to Giorgio. Maybe for the pull request. Anyway, that's been done and I'm the creator, and I'm satisfied this is fixed. Closing.
