### ISSUE TITLE
long script names cannot be cached

### ISSUE THREAD

**Issue by cchriste** [sci-visus/visus-issues#267]
15:47:40.5328 INFO DB_DISKACCESS.171 Failed to writeBlock filename(/Users/cam/code/nvisus/build/develop/./cached/time_0/range_0__field__TS___arr_____for__t_query_time_range_t__query_time_range_t______arr_arr_length__input_A_field___time___t___arr_arr_length__input_B_field___time___t___arr_arr_length__input_C_field___time___t___arr_arr_length__input_D_field___time___t___arr_arr_length__input_E_field___time___t_____output_Visus_Array_avg_arr__/00/00/00/00/00/00/00/06.zip) cannot create file and/or directory

Short scripts cache just fine.

visus.config is:

    <dataset name="Example with DiskAccess and MultipleAccess" url="http://atlantis.sci.utah.edu/mod_visus?dataset=pin2d"  >
        <access name="DiskAccess"  type='multiplex'>
        <access name="Example" type="DiskAccess" dir="./cached" compression="zip" nsamples="512 128" />
        <access type='network' chmod='r'   compression='zip' url="http://atlantis.sci.utah.edu/mod_visus?dataset=pin2d" />
      </access>     
</dataset>

The script is:

range=1; // width on either side of current to include in average
field="CLDLOW";
arr=[];
for (t=query_time-range;t<=query_time+range;t++)
{
arr[arr.length]=input.A[field+"?time="+t];
arr[arr.length]=input.B[field+"?time="+t];
arr[arr.length]=input.C[field+"?time="+t];
arr[arr.length]=input.D[field+"?time="+t];
arr[arr.length]=input.E[field+"?time="+t];
}
output=Visus.Array.avg(arr);

NOTE: I have verified that the comment isn't creating the bug. It's actually the length of the script. Remove a few of the lines inside the for loop and it will cache just fine.

**Comment by scrgiorgio** [comment]
I think I already solved the problem, now I'm using checksum (not encoding the script content anymore):

    //cannot use the real name... it creates directory names too long
    #if 0
    {
      VisusAssert(!field.name.empty());
      out<<"/"<<encode(field.name);
    }
    #else
    {
      VisusAssert(!field.checksum.empty());
      out<<"/"<<field.checksum;
    }
    #endif

could you double check?

**Comment by cchriste** [comment]
Yes, this is fixed.
