### ISSUE TITLE
force refresh doesn't fully refresh the first try

### ISSUE THREAD

**Issue by cchriste** [sci-visus/visus-issues#268]
I've been seeing this bug for months, but it's not been easy to reproduce. When a 3D dataset is loaded, zoom in a bit, then force refresh (using ctrl-r, not the menu). Most of the time (for me) the dataset only reloads to a low resolution and I have to force refresh again to get it to recompute to the correct resolution.

https://www.dropbox.com/s/qsk0eziuzt7zaxu/refresh_not_working.mov?dl=0

This 30-second video shows the problem. Note that each time the mouse circles the volume it's because the first time ctrl-r was pressed it did not refresh to the correct resolution, and ctrl-r had to be pressed again to get it to resolve the correct resolution.

**Comment by scrgiorgio** [comment]
I think I already solved this problem.
On windows now (12 may 2015) is working fine.
can you retry?

**Comment by cchriste** [comment]
This appears to be resolved.
