### ISSUE TITLE
VisusViewer iOS: 2 finger zoom doesn't work

### ISSUE THREAD

**Issue by amygooch** [sci-visus/visus-issues#271]
In VisusViewer on the iPad, 2 finger zoom shows the two touches and two circles of interaction, but doesn't change the zoom as I would expect it to.
Is this action mapped to something else?

**Comment by amygooch** [comment]
I've confirmed that this is a problem with VisusViewer (new or old UI) develop branch.
It is only a problem with 3D data.  2D zooms as you expect
The problem did not exist in SuperComputing2014 branch.

in 3D on the iPad you can see the correct 2 finger positions drawn with RenderGesters function, but the zoom level never updates.

**Comment by hoangthaiduong** [comment]
This could have some thing to do with the camera code that I modified some time ago. I knew at that time that there was a function that would not work with the new camera code, but couldn't trigger that function on my PC, so I just left a comment in the code. I will look into this as soon as I have time.

**Comment by hoangthaiduong** [comment]
@amygooch : since I don't have an iPad to test, do you mind making the following change to the code and test it?

file visuscpp/gui/gl/visus_gllookatcamera.cpp, line 405, which reads:
zoom(1.0/a);
replace this line with
forward(a < 1 ? forwardFactor : -forwardFactor);

**Comment by amygooch** [comment]
Acknowledged.. but it will take me a bit to get to this.. read sometime 2nd
week of June ;)

Amy

On Mon, May 18, 2015 at 8:46 PM, hoangthaiduong <notifications@github.com>
wrote:

> Assigned #271 <https://github.com/sci-visus/visus-issues/issues/271> to
> @amygooch <https://github.com/amygooch>.
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/sci-visus/visus-issues/issues/271#event-307993033>.
>



-- 

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Dr. Amy Ashurst Gooch          http://www.sci.utah.edu/people/agooch.html
<http://www.csc.uvic.ca/~agooch>
Research Scientist                                          amy.a.gooch at
gmail.com
Scientific Computing and Imaging                          agooch at
sci.utah.edu
University of Utah

(801)-649-3923    (SLC Virtual)
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

**Comment by amygooch** [comment]
On my iPad Air running iOS 8, the screen refresh is sluggish.. i.e.  two finger touch.. move them, and wait for the screen to update.. it often seems go "past" what I wanted the zoom to be; i.e. I lift up my fingers and it is still updating, still zooming.  Is it possible to keep the moves tighter related to the finger movements?  Perhaps this is an instance where we need to change the render?

**Comment by scrgiorgio** [comment]
This issue was moved to sci-visus/nvisusio#494
