### ISSUE TITLE
unexpected data relocation when crop is applied

### ISSUE THREAD

**Issue by cchriste** [sci-visus/visus-issues#272]
This uses the newly exposed "crop" functionality from https://github.com/sci-visus/nvisusio/commit/a0aed87582edcae71644bfbc3b41d2625651e84a

Using the following script in the processing node for a volume render of 2kbit1, we see that when a subsection of the volume is requested by the query, and the query is rotated, that the projected slice is not correctly transformed. 

https://www.dropbox.com/s/l15llydv4p15aa4/crop_slice_not_aligned_with_volume.mov?dl=0

It's not an urgent issue, but we want to keep track of it.

**Comment by scrgiorgio** [comment]
Duplicated issue? 
(I know you were the first to post, but Valerios' one contains the script to debug)

**Comment by cchriste** [comment]
Not sure what duplicate issue @scrgiorgio was referring to. Keeping this open since the same problem still exists. If we find @pascucci's issue with the script it can reference this and one of them can be closed.

**Comment by cchriste** [comment]
Duplicate of #287, which is also fixed now.
