### ISSUE TITLE
Shorter name for data node in explorer instead of URL

### ISSUE THREAD

**Issue by amygooch** [sci-visus/visus-issues#273]
Would it be possible to have the name for the loaded file instead of the lengthy url in the Explorer view (the name for the datasetnode)?

Amy
![screen shot 2015-03-11 at 4 24 57 pm](https://cloud.githubusercontent.com/assets/1149305/6607249/5f63bd70-c80b-11e4-8e17-3588e627e385.png)

**Comment by scrgiorgio** [comment]
mmm not sure what is the right way to do it.

For a local file it's simple: I can just use the basename of the file (i.e remove the path and the extension).

But for a network file it's not trivial: think about a commercial browser with some url, what is the short name we want to show? 

PS in Visus  99% the basename could be the http://...../mod_visus?dataset=name parameter... but I don't like to assume that urls are always 'mod_visus' urls (think about Google earth datasets)

**Comment by scrgiorgio** [comment]
This issue was moved to sci-visus/nvisusio#493
