### ISSUE TITLE
when a node is hidden in treeview, all active network queries should be stopped/deleted

### ISSUE THREAD

**Issue by cchriste** [sci-visus/visus-issues#274]
When we delete a node from the treeview, all its currently active network queries also stop. 

But when we simply hide a node, it's queued queries will still be active, sometimes for many minutes of data transfer.

We should remove active network queries when a node is hidden.

**Comment by scrgiorgio** [comment]
Try now:
https://github.com/sci-visus/nvisusio/commit/dbf9410095ded2d0592fbd55d96ac3786b33d6ea

**Comment by cchriste** [comment]
confirmed fixed
