### ISSUE TITLE
make statistics dialog text selectable

### ISSUE THREAD

**Issue by cchriste** [sci-visus/visus-issues#276]
Since we are often using exactly the data from the statistics dialog, it would be very helpful to be able to select it for copy and paste.

**Comment by cchriste** [comment]
For example, at the recent demos at LLNL, users asked to be able to see the current min/max in the palette. When showed where they could find the current min/max they then wanted to simply cut and paste the result back into the palette. Frustration ensued since neither solution worked.

**Comment by scrgiorgio** [comment]
This issue was moved to sci-visus/nvisusio#492
