### ISSUE TITLE
add support for new Visus Array operations

### ISSUE THREAD

**Issue by cchriste** [sci-visus/visus-issues#277]
Binarization and Bitwise operations
Automatic Normalization
Thresholding
Histogram Equilization and Weighting

This is not a complete list, but I wanted to start collecting ideas.

Essentially many of these are motivated by trying to write scripts that loop over the arrays to perform some operation. As this isn't possible, collective versions of these operations are necessary.

**Comment by cchriste** [comment]
Yes, I want to turn ViSUS into Matlab. :)

**Comment by cchriste** [comment]
Also need to actually implement missing but advertised operations like *median*.

**Comment by scrgiorgio** [comment]
This issue was moved to sci-visus/nvisusio#491
