### ISSUE TITLE
Please consider adding prev/next (<-- / -->) buttons for time slider

### ISSUE THREAD

**Issue by cchriste** [sci-visus/visus-issues#278]
Currently when the user want to select the timestep immediately before or after the current timestep, they must enter a value in the text field. 

The slider itself contains too many values to easily move by a single timestep when there are tens or hundreds of values, and typing is tedious.

**Comment by amygooch** [comment]
that's an easy one.. can do!


On Thu, Mar 12, 2015 at 2:54 PM, Cameron Christensen <
notifications@github.com> wrote:

> Assigned #278 <https://github.com/sci-visus/visus-issues/issues/278> to
> @amygooch <https://github.com/amygooch>.
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/sci-visus/visus-issues/issues/278#event-251217429>.
>



-- 
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
"Tell me and I'll forget; show me and I may remember; involve me and I'll
understand."
Chinese Proverb


~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Dr. Amy Ashurst Gooch          http://www.sci.utah.edu/people/agooch.html
<http://www.csc.uvic.ca/~agooch>
Research Scientist                                          amy.a.gooch at
gmail.com
Scientific Computing and Imaging                          agooch at
sci.utah.edu
University of Utah

979 353 1230    (Texas Virtual)
801 828 5038    (Cell)
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

**Comment by amygooch** [comment]
This has been added to develop branch (a bit ago)

**Comment by cchriste** [comment]
Thanks again, Amy!
