### ISSUE TITLE
some way to go to next timestep only when current one has finished caching

### ISSUE THREAD

**Issue by cchriste** [sci-visus/visus-issues#279]
I am creating demos and sometimes it would be helpful to have a section of the data cached to my system (hard to make a movie when you have to wait 60 seconds between each frame).

Currently I "hack" this by using 0 progression and setting the time interval to something conservative to ensure all the data is cached. But this ends up wasting time unnecessarily when a timestep loads more quickly than expected. 

I want some sort of feedback to tell the time slider to go to the next timestep when the first one has finished loading (or for example rendering if I am saving screenshots for a movie).

Because this is multifield data and I only want to cache one variable, simply copying the blocks directly is not an option. Also, it wouldn't suffice if I wanted to cache a computation rather than the original data.

**Comment by hoangthaiduong** [comment]
Cameron, as a temporary solution, you can use my fork of ViSUS here https://github.com/hoangthaiduong/nvisusio/tree/raycast

Set progression to 0, right click on any node, create a Screenshot node, then go to the time node and click "play". It will only advance time when the rendering has done for the current pass. It will also dump screenshots of each time step as a side effects.

**Comment by cchriste** [comment]
Hi Duong, that looks good. Unfortunately, I don't have time to merge anything right now, and the latest develop does a few things different with caching (things I require). But maybe this can be incorporated in the main develop branch. Have you submitted a pull request?

**Comment by hoangthaiduong** [comment]
I just merged my raycast branch with the latest develop (well... 1 commit behind the latest -- the one that changes the ArrayRenderNode). I have submitted a pull request but it will take some time before that gets merged (I need to address Giorgio's concerns). See if you can use my branch instead.

**Comment by scrgiorgio** [comment]
Duong, we need to talk, please see

https://docs.google.com/document/d/1dxcjp3TTmBsbGuyohqY8K7sfVDAwTSSUct3uHQIfg2U/edit?usp=sharing

**Comment by scrgiorgio** [comment]
See https://github.com/sci-visus/nvisusio/commit/63c312409efed3e3e8b1e1992f4a8afc02823a7a

**Comment by cchriste** [comment]
Now sure how it was implemented but waiting for all progressions levels to load now seems to be the default behavior. Even if the stepsize on the time slider is one second, it will wait however many seconds it takes to load all the levels. Closing the issue.
