### ISSUE TITLE
missing timesteps do not seem to be ignored

### ISSUE THREAD

**Issue by cchriste** [sci-visus/visus-issues#283]
Here is the visus.config for the dataset:
```xml
<dataset name="Pin2d (MultipleAccess)" url="$(atlantis)pin2d"  >
      <access name="MultipleAccess" type="MultipleAccess">
        <A type='multiplex'>
          <access type='disk'    chmod='rw' url='file://$(cache)/pin2d/A/visus.idx'  />
          <access type='network' chmod='r'   compression='zip' url="$(atlantis)pin2d/A" />
        </A>
        <B type='multiplex'>
          <access type='disk'    chmod='rw' url='file://$(cache)/pin2d/B/visus.idx'  />
          <access type='network' chmod='r'   compression='zip' url="$(atlantis)pin2d/B" />
        </B>
        <C type='multiplex'>
          <access type='disk'    chmod='rw' url='file://$(cache)/pin2d/C/visus.idx'  />
          <access type='network' chmod='r'   compression='zip' url="$(atlantis)pin2d/C" />
        </C>
        <D type='multiplex'>
          <access type='disk'    chmod='rw' url='file://$(cache)/pin2d/D/visus.idx'  />
          <access type='network' chmod='r'   compression='zip' url="$(atlantis)pin2d/D" />
        </D>
        <E type='multiplex'>
          <access type='disk'    chmod='rw' url='file://$(cache)/pin2d/E/visus.idx'  />
          <access type='network' chmod='r'   compression='zip' url="$(atlantis)pin2d/E" />
        </E>  
      </access>
    </dataset>   
```

And the script:
```javascript
f0=input.A.TS;
f1=input.B.TS;
f2=input.C.TS;
f3=input.D.TS;
f4=input.E.TS;
output=Visus.Array.avg([f0,f1,f2,f3,f4]);
```

Even though the output indicates they are ignored, the computation clearly includes fields of zeros. Note the data range in this image is lower than any of the actual (extant) data:
![average_missing_data_bug](https://cloud.githubusercontent.com/assets/1260945/6652005/891090c4-ca6f-11e4-98ff-e9c2c24e5943.png)

The average image looks like this:
![screenshot 2015-03-14 13 12 29](https://cloud.githubusercontent.com/assets/1260945/6652009/a2edbb02-ca6f-11e4-8415-238ba60959b4.png)

Output:

17:25:55.1342 INFO DB_MULTIPLEDATASET.820 Missing timestep(215) for input['D']...ignoring it
17:25:55.1686 INFO DB_MULTIPLEDATASET.820 Missing timestep(216) for input['D']...ignoring it
17:25:55.2032 INFO DB_MULTIPLEDATASET.820 Missing timestep(217) for input['D']...ignoring it
17:25:55.2368 INFO DB_MULTIPLEDATASET.820 Missing timestep(218) for input['D']...ignoring it
17:25:57.1756 INFO DB_MULTIPLEDATASET.820 Missing timestep(219) for input['D']...ignoring it
17:25:57.1919 INFO DB_MULTIPLEDATASET.820 Missing timestep(220) for input['B']...ignoring it
17:25:57.2064 INFO DB_MULTIPLEDATASET.820 Missing timestep(220) for input['D']...ignoring it
17:25:58.006 INFO DB_MULTIPLEDATASET.820 Missing timestep(221) for input['B']...ignoring it
17:25:58.7877 INFO DB_MULTIPLEDATASET.820 Missing timestep(221) for input['D']...ignoring it
17:25:59.5764 INFO DB_MULTIPLEDATASET.820 Missing timestep(222) for input['A']...ignoring it
17:25:59.5764 INFO DB_MULTIPLEDATASET.820 Missing timestep(222) for input['B']...ignoring it
17:25:59.5769 INFO DB_MULTIPLEDATASET.820 Missing timestep(222) for input['C']...ignoring it
17:25:59.5770 INFO DB_MULTIPLEDATASET.820 Missing timestep(222) for input['D']...ignoring it
17:25:59.5771 INFO DB_MULTIPLEDATASET.820 Missing timestep(222) for input['E']...ignoring it
17:25:59.5772 INFO DB_MULTIPLEDATASET.820 Missing timestep(223) for input['A']...ignoring it
17:25:59.5773 INFO DB_MULTIPLEDATASET.820 Missing timestep(223) for input['B']...ignoring it
17:25:59.5774 INFO DB_MULTIPLEDATASET.820 Missing timestep(223) for input['C']...ignoring it
17:25:59.5775 INFO DB_MULTIPLEDATASET.820 Missing timestep(223) for input['D']...ignoring it
17:25:59.5776 INFO DB_MULTIPLEDATASET.820 Missing timestep(223) for input['E']...ignoring it
17:25:59.5777 INFO DB_MULTIPLEDATASET.820 Missing timestep(224) for input['A']...ignoring it
17:25:59.5779 INFO DB_MULTIPLEDATASET.820 Missing timestep(224) for input['B']...ignoring it
17:25:59.5779 INFO DB_MULTIPLEDATASET.820 Missing timestep(224) for input['C']...ignoring it
17:25:59.5780 INFO DB_MULTIPLEDATASET.820 Missing timestep(224) for input['D']...ignoring it
17:25:59.5781 INFO DB_MULTIPLEDATASET.820 Missing timestep(224) for input['E']...ignoring it
17:25:59.5782 INFO DB_MULTIPLEDATASET.820 Missing timestep(225) for input['A']...ignoring it
17:25:59.5783 INFO DB_MULTIPLEDATASET.820 Missing timestep(225) for input['B']...ignoring it
17:25:59.5784 INFO DB_MULTIPLEDATASET.820 Missing timestep(225) for input['C']...ignoring it
17:25:59.5785 INFO DB_MULTIPLEDATASET.820 Missing timestep(225) for input['D']...ignoring it
17:25:59.5786 INFO DB_MULTIPLEDATASET.820 Missing timestep(225) for input['E']...ignoring it
17:25:59.5787 INFO DB_MULTIPLEDATASET.820 Missing timestep(226) for input['A']...ignoring it
17:25:59.5788 INFO DB_MULTIPLEDATASET.820 Missing timestep(226) for input['B']...ignoring it
17:25:59.5789 INFO DB_MULTIPLEDATASET.820 Missing timestep(226) for input['C']...ignoring it
17:25:59.5790 INFO DB_MULTIPLEDATASET.820 Missing timestep(226) for input['D']...ignoring it
17:25:59.5791 INFO DB_MULTIPLEDATASET.820 Missing timestep(226) for input['E']...ignoring it
17:25:59.6706 INFO DB_PROGRESSIVEQUERY.478 BoxQuery msec(4557) level(0/1/19/19) dims(1024 512 1 1 1) dtype(float32) filter(nullptr) access(yes) url(http://atlantis.sci.utah.edu/mod_visus?action=readdataset&dataset=pin2d) 
17:25:59.7056 INFO RENDERARRAY.230 dtype(float32) dimension(1024 512 1) dims(1024 512 1) transfered on GPU in msec(1)

**Comment by cchriste** [comment]
Please note: this functionality is actually working in a different context, using this script and the same dataset (same visus.config).

```javascript
t=query_time;
field="TS";
f0=input.A[field+"?time="+t];
f1=input.B[field+"?time="+(t-50)]; // doesn't exist!
f2=input.C[field+"?time="+t];
f3=input.D[field+"?time="+t];
f4=input.E[field+"?time="+t];
resultA=Visus.Array.avg([f0,f1,f2,f3,f4]);
resultB=Visus.Array.avg([f0,f2,f3,f4]); 
output=resultA;  
```

resultA and resultB are the same (exactly, per the statisticsnode)

So I'm not sure what's going on in the first situation. Different script...

**Comment by scrgiorgio** [comment]
Can you debug the two cases and tell me what's the difference?
From what I see in the code... if it's printing out "ignoring it" I should be fine.
Don't understand, need more details...

**Comment by cchriste** [comment]
Related to issue #368

**Comment by scrgiorgio** [comment]
This issue was moved to sci-visus/nvisusio#489
