### ISSUE TITLE
palette editor makes visus slow

### ISSUE THREAD

**Issue by pascucci** [sci-visus/visus-issues#284]
looks like the palette editor starts too many update events and make the system 
unusable (at least on Valerio's laptop)

**Comment by scrgiorgio** [comment]
can you retry?

There is a Timer in file visus_transferfunction.cpp/LINE 935 that "postpone" the publish of the palette in the dataflow. 

Maybe for your laptop the "publish every 500msec":

  start(500);

is too much? Can you try to change that value?

**Comment by cchriste** [comment]
This issue seems to affect many of us. Assigning to @anikethvenkat who has most recently complained about it. Maybe Aniketh can provide a reliable repro for the problem.

**Comment by scrgiorgio** [comment]
This issue was moved to sci-visus/nvisusio#488
