### ISSUE TITLE
Visit plugin not working well

### ISSUE THREAD

**Issue by pascucci** [sci-visus/visus-issues#285]
the visit plug in does not show the high resolution data.
There seem to be a complicated way to get there but seems very difficult for a non expert use.
We really need a version of the plug-in that just loads the full resolution data.

**Comment by pascucci** [comment]
- Disable Ram resource out of memory
- load full res by default (multires control optional)
- IDX file type detected automatically
- do not reload data unless resolution is changed
- set logical extents
- If optional multires becomes a problem just disable it

**Comment by pascucci** [comment]
Distributed loading. Verify how it is normally done.

**Comment by pascucci** [comment]
PIDX
- load full res 
- IDX file type detected automatically
- set logical extents
- run in distributed

**Comment by cchriste** [comment]
The existing plugin will load remote data (currently by hard coding a url). PIDX will not provide this functionality.

**Comment by cchriste** [comment]
At one time we considered this to be important, but as our story has evolved to "let them use visit like they always have" this type of remote access is no longer relevant. However it could be incorporated for demo purposes into the nvisusio plugin.

**Comment by cchriste** [comment]
Since Duong is working on VisIt plugin right now, I'm assigning this to him. We should decide whether we have the resources to fix/maintain the existing nvisusio-based plugin.

**Comment by cchriste** [comment]
Assigning this back to @pascucci to see if he wants to pursue anything here in light of the updated VisIt plugin.

**Comment by scrgiorgio** [comment]
This issue was moved to sci-visus/nvisusio#487
