### ISSUE TITLE
crop problems on a subvolume

### ISSUE THREAD

**Issue by pascucci** [sci-visus/visus-issues#287]
When I use the crop script below on a subvolume query (especially if rotate)
I get a few unexpected behaviours:
- the data is not updated properly (shows the original data instead of the average)
- the position of the slice is not as expected

// direction along which you computer the average 
dir = 0 ;

new_dim = input.dims ;
new_dim[dir]= 1;

output=Visus.Array.New([new_dim[0],new_dim[1],new_dim[2]],"Float32");

min_index = [0,0,0];
max_index = [input.dims[0]-1,input.dims[1]-1,input.dims[2]-1];

for (var i=0;i<input.dims[dir];i++)
{
min_index[dir] = i;
max_index[dir] = i;
slice=Visus.Array.crop(input,[[min_index[0],min_index[1],min_index[2]],[max_index[0],max_index[1],max_index[2]]]);
output=Visus.Array.add([output,slice]);
// Uncomment the line below for incremental display
// doPublish();
}

output=output/(1.0*input.dims[dir]);

**Comment by scrgiorgio** [comment]
Try now:

https://github.com/sci-visus/nvisusio/commit/57db12f2886f63f36c709eb9bfbfb6edd34508ad

(NOTE: if you rotate something bad could happen due to wrong GPU clipping planes)

**Comment by cchriste** [comment]
This is fixed. Closing for @pascucci. Also closing #272 which is the same issue.
