### ISSUE TITLE
image save

### ISSUE THREAD

**Issue by pascucci** [sci-visus/visus-issues#288]
It would be better if we could have a simplified frame saving that build automatically the file name so that
during a session one can save multiple images quickly.
It may be good to even have a shortcut.

**Comment by amygooch** [comment]
Acknowledged... This functionality is in there... I just need to expose it
to the user and set up a preference somewhere so it can be set by the user.

Will put it in asap

Amy

On Tuesday, March 17, 2015, Valerio Pascucci <notifications@github.com>
wrote:

> Assigned #288 <https://github.com/sci-visus/visus-issues/issues/288> to
> @amygooch <https://github.com/amygooch>.
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/sci-visus/visus-issues/issues/288#event-256891123>.
>


-- 
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
"Tell me and I'll forget; show me and I may remember; involve me and I'll
understand."
Chinese Proverb


~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Dr. Amy Ashurst Gooch          http://www.sci.utah.edu/people/agooch.html
<http://www.csc.uvic.ca/~agooch>
Research Scientist                                          amy.a.gooch at
gmail.com
Scientific Computing and Imaging                          agooch at
sci.utah.edu
University of Utah

979 353 1230    (Texas Virtual)
801 828 5038    (Cell)
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

**Comment by cchriste** [comment]
This is fixed and seems robust. Closing for @pascucci
