### ISSUE TITLE
Iso-contour's colour is not preserved after loading .xml

### ISSUE THREAD

**Issue by hoangthaiduong** [sci-visus/visus-issues#290]
How to reproduce:

1) Load ViSUS, open the dataset 2kbit1 (any data set will do)
2) Create an isocontour with iso value 68.785 (any value will do)
3) Save the scene to an .xml file and close ViSUS
4) Reopen ViSUS and load the scene just saved

![2kbit1_1](https://cloud.githubusercontent.com/assets/8607075/6770206/52ca1128-d0ca-11e4-8317-11998bc079f0.jpg)

![2kbit1_2](https://cloud.githubusercontent.com/assets/8607075/6770207/5301eff8-d0ca-11e4-841d-bf47b8a96892.jpg)

**Comment by hoangthaiduong** [comment]
The problem is in GLSingleSideMaterial::writeToObjectStream(). This line ostream.write("ambient"  ,this->ambient.toString() writes an empty string. I have fixed this bug but it will be a while before I can make a pull request, so Giorgio, if you can quickly fix it, please go ahead.

**Comment by scrgiorgio** [comment]
I think I already fixed it (see ColorObject class)
