### ISSUE TITLE
Isosurfaces become black when refined 

### ISSUE THREAD

**Issue by pascucci** [sci-visus/visus-issues#295]
I am displaying an isosrface in the usual green color
when it refines to full resolution it turns black

**Comment by cchriste** [comment]
I cannot reproduce this. Either it's been fixed or is a system-specific issue. 
Reassigning to @pascucci for clarification.

**Comment by scrgiorgio** [comment]
This issue was moved to sci-visus/nvisusio#482

**Comment by scrgiorgio** [comment]
I think this has been resolved some months ago

2016-03-18 0:36 GMT+01:00 Cameron Christensen <notifications@github.com>:
