### ISSUE TITLE
The time slider always have step 1

### ISSUE THREAD

**Issue by pascucci** [sci-visus/visus-issues#296]
If I set time stepping of 5 in a time slider and close the dialog, when I reopen the dialog the step is back to 1

**Comment by scrgiorgio** [comment]
Try now.

https://github.com/sci-visus/nvisusio/commit/1b4d883951b2d51b337c45238dd2b8b77a5bfc43

**Comment by cchriste** [comment]
This issue has been resolved. Closing for @pascucci
