### ISSUE TITLE
Multiple edit windows open 

### ISSUE THREAD

**Issue by AaronBehunin** [sci-visus/visus-issues#297]
1.  Double click any node
2. double click same node again

it is possible to have the same edit window open multiple times.

**Comment by AaronBehunin** [comment]
Here is a screenshot
![double](https://cloud.githubusercontent.com/assets/10467750/6924259/1224e224-d78c-11e4-9b7c-275274688c0f.png)

**Comment by cchriste** [comment]
One might argue that this is by design, but I agree that it can be confusing. 
Assigning to @scrgiorgio for consideration.

**Comment by scrgiorgio** [comment]
This issue was moved to sci-visus/nvisusio#481
