### ISSUE TITLE
enable-viewdep edit window too small

### ISSUE THREAD

**Issue by AaronBehunin** [sci-visus/visus-issues#298]
1. open render of choice
2. click slice1 node arrow
3. double click enable-viewdep node

The window is very hard to move around. 
there is only a small area in which you can move by dragging.

![small](https://cloud.githubusercontent.com/assets/10467750/6924361/ea875aac-d78c-11e4-9c44-058ce156c636.png)

**Comment by cchriste** [comment]
We have a number of similar issues with default window sizes. Assigning to @scrgiorgio who might have a general solution to improve the situation.

**Comment by scrgiorgio** [comment]
This issue was moved to sci-visus/nvisusio#480
