### ISSUE TITLE
Save opened diaglogs and their positions

### ISSUE THREAD

**Issue by hoangthaiduong** [sci-visus/visus-issues#299]
It would be nice for ViSUS to have an option to save the opened dialogs and their positions. This is extremely useful when preparing screenshots/movies. For example, we may capture the screen in multiple sessions and want a consistent GUI layout among the sessions.

**Comment by scrgiorgio** [comment]
Really don't think this is something we should solve now.
What if you record a movie on a monitor with a certain resolution and play it on a iphone?
More comments are welcome...

**Comment by cchriste** [comment]
I've been recording a lot of videos for the climate simulation work and I've also wanted to have something like this, where a scene re-opens all the opened windows (duplicates as described in #297 notwithstanding) in the same configuration as the original scene. Even if the monitor resolution has changed, which is a corner case anyway, the general layout could be preserved.

**Comment by scrgiorgio** [comment]
This issue was moved to sci-visus/nvisusio#479
