### ISSUE TITLE
Building shared library on Windows fails

### ISSUE THREAD

**Issue by hoangthaiduong** [sci-visus/visus-issues#300]
Building ViSUS with BUILD_SHARED_LIBS turn on does not succeed. Here is a screenshot of the errors:

![screenshot - 3_4_2015 5_22_03 pm](https://cloud.githubusercontent.com/assets/8607075/6983409/2d8a0502-da26-11e4-9ffd-8ce8533c897e.png)

**Comment by scrgiorgio** [comment]
https://github.com/sci-visus/nvisusio/commit/e31af7451757502b4f901258491d8bb8f0a85731
