### ISSUE TITLE
kdquery with cache hangs waiting for locks

### ISSUE THREAD

**Issue by cchriste** [sci-visus/visus-issues#301]
Latest develop has a problem with KdQuery when caching results with a multiplx that results in a perpetual (non-responsive) hang while repeatedly displaying the following type of error:

```
21:45:18.8248 INFO FILE.316 [PID=3533] waiting for lock on /Users/cam/visus/cached_files/Sam03/visus/00/0400.bin.lock
```

How to reproduce:

1) Use the following in your visus.config:

```xml
  <alias key="atlantis" value="http://atlantis.sci.utah.edu/mod_visus?dataset=" /> 
  <alias key="cache" value="$(VisusCacheDirectory)"/> 

    <dataset name="Sam03" url="$(atlantis)Sam03"  >
      <access name="multiplex"  type='multiplex'>
        <access name="disk"   type="disk"    chmod='rw' compression='none' url="$(cache)/Sam03/visus.idx" />
        <access name="remote" type="network" chmod='r'  compression='zip' />
      </access>
    </dataset>
```

2) Open the dataset, add KdQuery
3) increase the size of the query to the size of the volume
4) deselect "enable_viewdep" in the KdQuery (not in the parent!)

--> You will see the following appear very quickly, and the application becomes non-responsive. After some time the "waiting for lock" will timeout, only to be replaced immediately by waiting for another lock.

**Comment by scrgiorgio** [comment]
Can you retry? Maybe this problem has been resolved a while back.
On windows (latest develop) it works fine, and I don't get the "waiting for lock" message.
It's a little unresponsive but I guess it's the huge Kd-texture.

**Comment by cchriste** [comment]
Confirmed. This no longer seems to be an issue.
