### ISSUE TITLE
crash when loading multiple volumes

### ISSUE THREAD

**Issue by cchriste** [sci-visus/visus-issues#303]
In the old (sc14) develop we were able to load a group of files and interact relatively well. This same group now crashes, as does any group when there are more than say 25 members. 

This is the error in the console:
```
16:40:12.7200 ERROR SEMAPHORE.APPLE.36 critical error, cannot create the semaphore
libc++abi.dylib: libc++abi.dylib: terminating with uncaught exception of type Visus::VisusRunTimeExceptionterminating with uncaught exception of type Visus::VisusRunTimeException
```

Steps to reproduce:
1) Load a lot of idx volume (more than 25). You can use the new gidx feature below, but it's not necessary.
2) You will only see one slice. This can be "fixed" by removing the enable_viewdep child of the first slice, as shown in the attached image.
--> after that things will quickly crash

![screenshot 2015-04-06 16 40 17](https://cloud.githubusercontent.com/assets/1260945/7005159/32b0949c-dc7e-11e4-8727-59d5ed1d7fd1.png)

Note: I introduced a new "gidx" format for "groups of idx", which can be used to load a group of local or remote idx files.  Note: you need the code from this pull request to load a gidx volume: https://github.com/sci-visus/nvisusio/pull/350. There is an example gidx in docs/examples/gidx. (Note: the crash occurs regardless of how you open the volumes, and it doesn't matter if they are local or remote).

This bug is high priority because the multiple volume functionality is being utilized for an SC submission.

**Comment by scrgiorgio** [comment]
I'm not sure if it's a problem related to the way how I'm generating names:

    static Atomic::internal_t __semnum__ = 0; 
    int semnum =Atomic::increment(&__semnum__);
    char name[32];
    sprintf(name, "/vis_sem-%d-%4.4d", getpid(),semnum);

or if we are creating too much semaphores (is there a max number of named semaphore we can create?).

I would try

1) Chage permissions 0600 to something different (maybe 0)?

2) set the name to something different (like using a rand() number inside)

3) adding a sem_unlink after the sem_close (eventually checking the return code)

4) adding a sem_unkink before sem_open (without checking the return code)

5) The very last alternative (which I hate) is to use a portable implementation of semaphores for Posix system (see Poco C++ library: file Semaphore_POSIX.cpp)

Let me know.

**Comment by cchriste** [comment]
It does seem to be a problem with a limit on the maximum number of semaphores. I read about it and also experimented using this code, which shows the limit to be ~250. The solution may be to use "grand central dispatch" semaphores. I'm experimenting with this now...

```c++
    //try creating a lot of semaphores
    CriticalSection lock;
    {
      ScopedLock slock(lock);
      sem_t* sems[10000];
      int semnum=0;
      char name[32];
      for (int i=0;i<10000;i++)
      {
        sprintf(name, "/vis_sem-%d-%4.4d", getpid(),semnum++);
        sems[i] = sem_open(name,O_CREAT,0600,initial_value); 
        if (sems[i]==(sem_t*)SEM_FAILED) Application::getCurrent()->throwError(__FILE__,__LINE__,String("critical error, cannot create the semaphore:")+name);
        sem_unlink(name);
      }
      for (int i=0;i<10000;i++)
      {
        sem_close(sems[i]);
      }
    }
```

**Comment by cchriste** [comment]
Using GCD semaphores resolves the problem, probably because these do not allocate a shared OS resources unless there is actually a need for interprocess communication.

Here is some more information about them:
https://developer.apple.com/library/ios/documentation/Performance/Reference/GCD_libdispatch_Ref/index.html#//apple_ref/c/func/dispatch_semaphore_wait

And here is the pull request to add them:
https://github.com/sci-visus/nvisusio/pull/351

**Comment by scrgiorgio** [comment]
can I close this? I think we are now using the new OSX semaphores...

**Comment by cchriste** [comment]
I am assigning this to Aniketh to verify since he is working with multi-volume datasets. 

Aniketh, we have the 39-volume (MM353?) dataset from the Angelucci lab, and I have some synthetic datasets with many more than this. I'll bring them for our meeting today.

**Comment by cchriste** [comment]
I suspect we still have issues when loading 10s of volumes, but I'll close this for now and we can reopen it if/when we start to have problems.
