### ISSUE TITLE
range seems to be lost though midx

### ISSUE THREAD

**Issue by pascucci** [sci-visus/visus-issues#305]
If a load a file that has a range it is used.
If the same file is loaded via midx the original range seems lost.
This is currently a problem for the angelucci data but seems to have the potential to be a problem in general.

**Comment by scrgiorgio** [comment]
In general any MIDX file (==multiple dataset) does not have "static" fields but only dynamic fields (== fields computed by a certain javascript expression).

99% of the times I don't know how to guess the range of that expression. The remaining 1% is when I have a trivial expression where the fieldname is exactly the fieldname of the internal dataset (for example 'temperature').

But after Javascript::eval even that range is lost... any suggestion?

**Comment by scrgiorgio** [comment]
This issue was moved to sci-visus/nvisusio#477
