### ISSUE TITLE
ViSUS DOes not compile at ORNL

### ISSUE THREAD

**Issue by ptbremer** [sci-visus/visus-issues#306]
Curl does not compile with any compiler on rhea the analysis cluster at ORNL. Neither PGI, intel, nor gnu will compile

/ccs/home/bremer/Code/nvisusio/libs/curl-7.23.1/lib/if2ip.c:53:23: fatal error: stropts.h: No such file or directory

**Comment by ptbremer** [comment]
Apparently the 

#ifdef HAVE_STROPTS_H

is set incorrectly. I can replace this include with the following and things compile

//#  include <stropts.h>                                                                                                                                                
#include <sys/ioctl.h>

**Comment by cchriste** [comment]
Assigning back to @ptbremer to test with current version.

**Comment by scrgiorgio** [comment]
This issue was moved to sci-visus/nvisusio#476
