### ISSUE TITLE
ViSUS Does not compile on titan

### ISSUE THREAD

**Issue by ptbremer** [sci-visus/visus-issues#307]
The CMake fails for all compilers on Titan at ORNL. I think the cmake might have issues with the compiler wrappers

-- Check for working C compiler: /ccs/compilers/gcc/rhel6-x86_64/4.7.1/bin/cc -- broken
CMake Error at /autofs/na4_sw/xk6/cmake/2.8.10.2/cle4.0_gnu4.7.2/share/cmake-2.8/Modules/CMakeTestCCompiler.cmake:61 (message):
  The C compiler "/ccs/compilers/gcc/rhel6-x86_64/4.7.1/bin/cc" is not able
  to compile a simple test program.

  It fails with the following output:

   Change Dir: /ccs/home/bremer/csc094/build/nvisusio-build/CMakeFiles/CMakeTmp

Other combinations get a bit further 

-- Check for STD namespace
CMake Error at /autofs/na4_sw/xk6/cmake/2.8.10.2/cle4.0_gnu4.7.2/share/cmake-2.8/Modules/CMakeCXXInformation.cmake:37 (get_filename_component):
  get_filename_component called with incorrect number of arguments
Call Stack (most recent call first):
  CMakeLists.txt:2 (PROJECT)

CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage
CMake Error: Internal CMake error, TryCompile configure of cmake failed
-- Check for STD namespace - not found
-- Check for ANSI scope
CMake Error at /autofs/na4_sw/xk6/cmake/2.8.10.2/cle4.0_gnu4.7.2/share/cmake-2.8/Modules/CMakeCXXInformation.cmake:37 (get_filename_component):
  get_filename_component called with incorrect number of arguments
Call Stack (most recent call first):
  CMakeLists.txt:2 (PROJECT)

CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage
CMake Error: Internal CMake error, TryCompile configure of cmake failed
-- Check for ANSI scope - not found
-- Check for sstream
CMake Error at /autofs/na4_sw/xk6/cmake/2.8.10.2/cle4.0_gnu4.7.2/share/cmake-2.8/Modules/CMakeCXXInformation.cmake:37 (get_filename_component):
  get_filename_component called with incorrect number of arguments
Call Stack (most recent call first):
  CMakeLists.txt:2 (PROJECT)

**Comment by cchriste** [comment]
Assigning back to @ptbremer to test with current version.

**Comment by scrgiorgio** [comment]
This issue was moved to sci-visus/nvisusio#475
