### ISSUE TITLE
The time slider does not streatch when extended

### ISSUE THREAD

**Issue by pascucci** [sci-visus/visus-issues#310]
The time slider should extend to the entire width of the window so that when enlarged one
gets greater precision. Now it remains short.

P.s.
I wonder how do I know if this should be assigned to be assigned to Giorgio or Amy or .....

**Comment by scrgiorgio** [comment]
should be assigned to amy

**Comment by amygooch** [comment]
Fixed this in my branch... will use a pull request and confirm it works in develop when that is accepted

**Comment by amygooch** [comment]
Fixed in developed, returning to Valerio to be resolved

**Comment by cchriste** [comment]
Confirmed this is fixed. Closing for @pascucci
