### ISSUE TITLE
OpenGL/ Win 64     Bookmarks causing crashes

### ISSUE THREAD

**Issue by AaronBehunin** [sci-visus/visus-issues#311]
The following bookmarks cause Visus to crash when running its time feature:

In atlantis/ARUP/
http://atlantis.sci.utah.edu/mod_visus?dataset=ldav2d

in Atlantis/Biology/
http://atlantis.sci.utah.edu/mod_visus?dataset=M323_Sec31

**Comment by AaronBehunin** [comment]
The following bookmarks cause Visus to Crash when Trying to open the bookmark

in Atlantis/VolcanoEnsemble/
http://atlantis.sci.utah.edu/mod_visus?dataset=A2d
http://atlantis.sci.utah.edu/mod_visus?dataset=A3d
http://atlantis.sci.utah.edu/mod_visus?dataset=A3d1
http://atlantis.sci.utah.edu/mod_visus?dataset=B2d
http://atlantis.sci.utah.edu/mod_visus?dataset=B3d
http://atlantis.sci.utah.edu/mod_visus?dataset=B3d1
http://atlantis.sci.utah.edu/mod_visus?dataset=C2d
http://atlantis.sci.utah.edu/mod_visus?dataset=C3d
http://atlantis.sci.utah.edu/mod_visus?dataset=C3d1
http://atlantis.sci.utah.edu/mod_visus?dataset=E2d
http://atlantis.sci.utah.edu/mod_visus?dataset=E3d
http://atlantis.sci.utah.edu/mod_visus?dataset=E3d1
http://atlantis.sci.utah.edu/mod_visus?dataset=E2d
http://atlantis.sci.utah.edu/mod_visus?dataset=E3d
http://atlantis.sci.utah.edu/mod_visus?dataset=E3d1
http://atlantis.sci.utah.edu/mod_visus?dataset=all2d
http://atlantis.sci.utah.edu/mod_visus?dataset=all3d
http://atlantis.sci.utah.edu/mod_visus?dataset=all3d1
http://atlantis.sci.utah.edu/mod_visus?dataset=nopin2d
http://atlantis.sci.utah.edu/mod_visus?dataset=nopin3d
http://atlantis.sci.utah.edu/mod_visus?dataset=nopin3d1
http://atlantis.sci.utah.edu/mod_visus?dataset=pin2d
http://atlantis.sci.utah.edu/mod_visus?dataset=pin3d
http://atlantis.sci.utah.edu/mod_visus?dataset=pin3d1
http://atlantis.sci.utah.edu/mod_visus?dataset=two47_2d
http://atlantis.sci.utah.edu/mod_visus?dataset=two47_3d
http://atlantis.sci.utah.edu/mod_visus?dataset=two47_3d1

**Comment by cchriste** [comment]
I'm not sure what the issues were here. These datasets load okay using the latest viewer. In general, perhaps we should ensure all bookmarks in the default visus.config are functional. Assigning to myself to check, will close when verified.

**Comment by scrgiorgio** [comment]
This issue was moved to sci-visus/nvisusio#473
