### ISSUE TITLE
OpenGL/ Win64   bookmarks don't open

### ISSUE THREAD

**Issue by AaronBehunin** [sci-visus/visus-issues#312]
The following bookmarks return a open file error when you click on them:

in CIBC/
http://remus.chpc.utah.edu:8080/mod_visus?dataset=single_coal_jet-time    

This is also the path that Visus attempts to open upon startup

http://remus.chpc.utah.edu:8080/mod_visus?dataset=single_coal_jet
http://remus.chpc.utah.edu:8080/mod_visus?dataset=alstom_boiler

in KAUST/
http://fen4.hpc.kaust.edu.sa/mod_visus?dataset=flame
http://fen4.hpc.kaust.edu.sa/mod_visus?dataset=KB-E0010

in Atlantis/ANL/
http://atlantis.sci.utah.edu/mod_visus?dataset=lial-h2o

in Atlantis/PNNL(cii)/
http://atlantis.sci.utah.edu/mod_visus?dataset=Sam03_uint8

**Comment by cchriste** [comment]
Closing as dup of #311
