### ISSUE TITLE
OpenGL/ Win64 Booksmarks have bad data

### ISSUE THREAD

**Issue by AaronBehunin** [sci-visus/visus-issues#313]
All these Bookmarks have bad data representaitons in them.

in Atlantis/ARUP/
http://atlantis.sci.utah.edu/mod_visus?dataset=rbccase4_sub     
          did not layer it's scan data

in Atlantis//Panoramas/
http://atlantis.sci.utah.edu/mod_visus?dataset=paris_map
              has yellow and gray bars

http://atlantis.sci.utah.edu/mod_visus?dataset=slc_library_wavelet
              is segmented and oriented sideways

in   Atlantis/Satellite/
http://atlantis.sci.utah.edu/mod_visus?dataset=san_antonio  
http://atlantis.sci.utah.edu/mod_visus?dataset=san_antonio_nobbox
                has no data

**Comment by AaronBehunin** [comment]
The following panoramas load upside down:

in Atlantis/Geology/
http://atlantis.sci.utah.edu/mod_visus?dataset=outcrop   

in Atlantis/Panoramas/
http://atlantis.sci.utah.edu/mod_visus?dataset=SLC_library    
http://atlantis.sci.utah.edu/mod_visus?dataset=SLC_library_subsample
http://atlantis.sci.utah.edu/mod_visus?dataset=SLC_library_wavelet
http://atlantis.sci.utah.edu/mod_visus?dataset=SLC_library_wavelet_subsample
http://atlantis.sci.utah.edu/mod_visus?dataset=SLC_panorama
http://atlantis.sci.utah.edu/mod_visus?dataset=deer_valley_400
http://atlantis.sci.utah.edu/mod_visus?dataset=deer_valley_600
http://atlantis.sci.utah.edu/mod_visus?dataset=lake_wavelet
http://atlantis.sci.utah.edu/mod_visus?dataset=paris
http://atlantis.sci.utah.edu/mod_visus?dataset=paris_orig
http://atlantis.sci.utah.edu/mod_visus?dataset=paris_subsampled
http://atlantis.sci.utah.edu/mod_visus?dataset=peak_wavelet
http://atlantis.sci.utah.edu/mod_visus?dataset=south_tower_wavelet
http://atlantis.sci.utah.edu/mod_visus?dataset=west_tower_wavelet
http://atlantis.sci.utah.edu/mod_visus?dataset=mount_rushmore

**Comment by AaronBehunin** [comment]
the Following bookmarks have bad images inside their time sequence

in Atlantis/VolcanoEnsemble/
http://atlantis.sci.utah.edu/mod_visus?dataset=novolcanoA_2d
http://atlantis.sci.utah.edu/mod_visus?dataset=novolcanoB_2d
http://atlantis.sci.utah.edu/mod_visus?dataset=novolcanoC_2d
http://atlantis.sci.utah.edu/mod_visus?dataset=novolcanoD_2d
http://atlantis.sci.utah.edu/mod_visus?dataset=novolcanoE_2d
http://atlantis.sci.utah.edu/mod_visus?dataset=volcanoA_2d
http://atlantis.sci.utah.edu/mod_visus?dataset=volcanoB_2d
http://atlantis.sci.utah.edu/mod_visus?dataset=volcanoC_2d
http://atlantis.sci.utah.edu/mod_visus?dataset=volcanoD_2d
http://atlantis.sci.utah.edu/mod_visus?dataset=volcanoE_2d

**Comment by cchriste** [comment]
Some of these are indeed bad volumes. Closing this as dup of #311 (it will be referenced in #311, so the list will not be lost).
