### ISSUE TITLE
importing visuspy without using it causes segfault on exit

### ISSUE THREAD

**Issue by cchriste** [sci-visus/visus-issues#314]
This isn't a critical issue. I'm reporting it because I spent a bunch of time chasing it and it's cause wasn't obvious.

```python
from visuspy import *
if __name__ == '__main__':

    segfault=True

    if not segfault:
        app=Application()
        app.setCommandLine("")
        app.useModule(IdxModule.getSingleton())  
    else:
        print "doing nothing"

```

I tried invoking pdb.set_trace at the end, which produces this suspicious exception for both setfault=True and segfault=False cases:
```
Exception AttributeError: "'NoneType' object has no attribute 'path'" in <function _remove at 0x10d8f6668> ignored
```

**Comment by scrgiorgio** [comment]
This issue was moved to sci-visus/nvisusio#472
