### ISSUE TITLE
implement "add" action for mod_visus

### ISSUE THREAD

**Issue by cchriste** [sci-visus/visus-issues#315]
e.g. 
http://atlantis.sci.utah.edu/mod_visus?action=add&url=file:///path/to/new/volume.idx

This should incorporate the new dataset into the existing visus.config so future resets will preserve the addition.

**Comment by scrgiorgio** [comment]
https://github.com/sci-visus/nvisusio/commit/885554e55b03f58e4d162465abcb04d13d609470

**Comment by cchriste** [comment]
perfect
