### ISSUE TITLE
module arrangement doesn't make sense

### ISSUE THREAD

**Issue by cchriste** [sci-visus/visus-issues#316]
"NeuroTracker" seems to be a home for several features that are either more general than neuronal microscopy or simply unrelated. Suggest rearranging:

Topology: 
 - MSC
 - Min Tree
 - Max Tree

Rendering: 
 - Point Render
 - etc.

NeuroTracker:
 - Voxelscoop (note this currently utilizes a gpl class, Rayburst)

There is no other specialized code for NeuroTracker, though it would make sense to use this for code targeted for our current neuronal microscopy project.

**Comment by scrgiorgio** [comment]
ok I agree 100%
 what about sending me a pull request with changes?

**Comment by scrgiorgio** [comment]
Try now. See https://github.com/sci-visus/nvisusio/commit/311f7c48129b976766db738100622ef78625a233

**Comment by cchriste** [comment]
Sorry, didn't see your comment from May. I need to go through all my issues (github :) and see what is waiting on me.
