### ISSUE TITLE
mod_visus doesn't use multiplex access

### ISSUE THREAD

**Issue by cchriste** [sci-visus/visus-issues#317]
Visus server is not utilizing the access specified in visus.config. 
Here is a simple way to reproduce:

Create ondemand_checkerboard.idx:
```
(version)
6
(logic_to_physic)
1 0 0 0 0 1 0 0 0 0 1 0 0 0 0 1
(box)
0 2047 0 2047 0 0 0 0 0 0
(fields)
data float32 format(0) 
(bits)
V0101010101010101010101
(bitsperblock)
16
(blocksperfile)
64
(interleave block)
0
(filename_template)
./ondemand_checkerboard/%02x.bin
```

Add this to your visus.config:
```xml
<alias key="data"  value="/path/to/nvisusio/docs/examples/ondemand"/>
<alias key="cache" value='$(VisusCacheDirectory)' />
<dataset name="Test_Server_Multiplex" url="$(data)/ondemand_checkerboard.idx" permissions="public">
  <access name="Multiplex" type="multiplex">
    <access type='disk'           chmod='rw'  url="file://$(cache)/test_server_multiplex/visus.idx"/>
    <access type='ondemand'       ondemand="checkerboard"    />
  </access>
</dataset>
```

When this dataset is loaded with client, a block query will make it to the ondemand access:
![screenshot 2015-05-01 22 12 48](https://cloud.githubusercontent.com/assets/1260945/7436910/e3f75020-f05a-11e4-8c29-f9d5a1d6337e.png)

However, when loaded by the server, the multiplex access is never used. In the case of this example, the (non-existent) cache file is read. Other examples that were tried will simply read the file that exists.

This is an urgent issue for the esg ondemand data conversion server.

**Comment by cchriste** [comment]
Same problem. 

Per Valerio's suggestion, reduced visus.config to a single entry:
```xml
<?xml version="1.0" ?>
<visus>
  <dataset name="checkerboard" url="file:///Users/cam/visus/checkerboard3d.idx" permissions="public">
    <access name="Multiplex" type="multiplex">
      <access type='disk'           chmod='rw'  url="file://$(VisusCacheDirectory)/checkerboard3d/visus.idx"/>
      <access type='ondemandaccess' chmod='r'   ondemand="checkerboard" />
    </access>
  </dataset>
</visus>
```

Includes fix for issue #248 that removes code that searches for url when a matching alias isn't found.

**Comment by scrgiorgio** [comment]
maybe solved ?

**Comment by cchriste** [comment]
Confirmed this is fixed.
