### ISSUE TITLE
Make default mod_visus url produce web page listing available volumes 

### ISSUE THREAD

**Issue by cchriste** [sci-visus/visus-issues#319]
http://server.domain.com/mod_visus should bring up a web page. Initially this can simply list the same results as *action=list* but a more polished page can eventually be produced.

**Comment by scrgiorgio** [comment]
https://github.com/sci-visus/nvisusio/commit/d6714e94a09d9c9d6f313bb7ef210902cd2c96c7

**Comment by cchriste** [comment]
works great!

**Comment by cchriste** [comment]
I'm re-opening this feature request with a one-up: make mod_visus provide a visus.config for itself using *action=getConfig*

**Comment by cchriste** [comment]
Note: I want this to be a default behavior, and the getconfig to be based on action.

**Comment by scrgiorgio** [comment]
This issue was moved to sci-visus/nvisusio#471
