### ISSUE TITLE
Redundant includes

### ISSUE THREAD

**Issue by hoangthaiduong** [sci-visus/visus-issues#320]
There are many redundant includes in each .cpp file. For example, every `.cpp` file in `visusappkit` includes `visus_appkit.h`, but `visus_appkit.h` in turn includes every single `.h` file in the `visusappkit` project, which can slow down the compilation time a lot.

I guess the reason why `visus_appkit.h` includes other `.h` files is that we want to be able to build `visusappkit` as a library? But that doesn't explain why every internal `.cpp` file in `visusappkit` should include `visus_appkit.h`.

I can go ahead and resolve this issue, but I want a confirmation that this is really an issue and not something that I overlooked.

![visus_appkit_include_graph](https://cloud.githubusercontent.com/assets/8607075/7515725/2e41e7e6-f4d2-11e4-83b8-7f62e2e04264.jpg)

**Comment by scrgiorgio** [comment]
This was a choice deliberately made in the past: to have a Visus C++ module-like compilation. i.e. one main include file (like visus_appkit.h) that includes all the necessary header.  In this way, at the beginning of the file, it's very simple to know what are the module inter-dependecies:

#ifndef __VISUS_APPKIT_H
#define __VISUS_APPKIT_H

#include <visuscpp/gui/visus_gui.h>
#include <visuscpp/idx/visus_idx.h>

#if VISUS_BUILD_CUDA
#include <visuscpp/cuda/visus_cuda.h>
#endif

In the past every *.cpp files had tons of #ifdef and the portability of the code was a nightmare.

Under the assumption that *.h files are pretty stable (== the implementation changes more that the declaration) I still think that this solution is a good compromise.

Usually to speed up the compilation I'm enabling "precompilation headers" (==one *.cpp files that speed up the compilation of all other files, like visus_appkit.cpp). What's your platform?

Let me know.

**Comment by cchriste** [comment]
Duong, do you feel that we can now close this issue?

**Comment by cchriste** [comment]
Closing this issue. The compile performance with the new include structure is much better.
