### ISSUE TITLE
add "import datasets/config" feature

### ISSUE THREAD

**Issue by cchriste** [sci-visus/visus-issues#321]
When a new dataset is added to the server using the new AddDataset functionality from https://github.com/sci-visus/nvisusio/commit/885554e55b03f58e4d162465abcb04d13d609470, its description needs to be merged with the existing visus.config on the server.

The desire to import additional datasets into one's "bookmarks" also exists at the user level. For example, when a user requests a climate dataset as an IDX, they are given a new visus.config containing all the idx volumes corresponding to the selected climate dataset (one per domain). Naturally they might wish to add these to their existing bookmarks.

Perhaps a <group> scope in visus.config would enable mixing of existing configs without creating conflicts with templates.

**Comment by scrgiorgio** [comment]
I think it's already doing it ("its description needs to be merged with the existing visus.config on the server.")

What is exactly missing?

**Comment by cchriste** [comment]
The request is to integrate a new visus.config into an existing visus.config. 

The idea proposed is that we can create a group inside an existing config that serves as a scope so that name conflicts are avoided.

**Comment by cchriste** [comment]
This is fixed by https://github.com/sci-visus/nvisusio/commit/c142f135ad1ef1a4dfdb2e91c76b8c94cb76614e
