### ISSUE TITLE
Do not allow add_dataset of existing dataset (based on name)

### ISSUE THREAD

**Issue by cchriste** [sci-visus/visus-issues#322]
add_dataset functionality (#315) currently allows multiple datasets with the same name to be added.

Multiple datasets with the same name should not be allowed.

**Comment by cchriste** [comment]
Unfortunately this may not play well with xml= syntax. I'm making this issue low priority for now.

**Comment by scrgiorgio** [comment]
I think that AddDataset is right now more a ReplaceDataset... otherwise we would need to add also the RemoveDataset.
What do you think?

**Comment by cchriste** [comment]
This is fixed by https://github.com/sci-visus/nvisusio/commit/98622760ad8f8dfc7c477404e5d0bdfc9e0c7349.
New datasets of the same name (even using xml syntax) will be ignored.

There is currently no "remove" or "replace" functions. Let's make a separate feature request issue if they are desired.
