### ISSUE TITLE
integrate rendering parameters for kd render

### ISSUE THREAD

**Issue by cchriste** [sci-visus/visus-issues#323]
The kd renders seem to have two primary challenges: rendering *order* (effects 3D only) and rendering *parameters* such as data range.

Images such as the following 2D view show a scalar field for which the data range of individual blocks is different. The rendering shows discontinuities in the shading between blocks because their data range is each calculated independently. We need a way to collect these parameters for all the blocks such that the data range used by the individual kd renders is the union of the data ranges of all of the blocks. 

![screenshot 2015-05-16 01 03 12](https://cloud.githubusercontent.com/assets/1260945/7670424/2d56d1ca-fcac-11e4-9265-6127424538f0.png)

Unfortunately, Kd render also seems to ignore user array range in palette, so a correct result can only be seen with another renderer.

**Comment by scrgiorgio** [comment]
This issue was moved to sci-visus/nvisusio#469
