### ISSUE TITLE
Crash when reading 3D bricked dataset

### ISSUE THREAD

**Issue by hoangthaiduong** [sci-visus/visus-issues#324]
For a 3D bricked dataset, retrieving a slice using PointQuery does not work. It crashes at the following line in visus_db_brickdataset.cpp:

```QuerySamples ret=QuerySamples::create(up_logic_box,up_logic_delta);```
The problem is that `up_logic_box` is empty.

If you need a dataset to work with, please find it here https://www.dropbox.com/sh/y8gm0azcwxwq9s2/AADISFoZXeHVAh6_eKAXAiQba?dl=0

**Comment by scrgiorgio** [comment]
See https://github.com/sci-visus/visus-issues/issues/324
(note I added your 3d brick dataset inside visus for testing)

**Comment by hoangthaiduong** [comment]
Fixed. Thanks Giorgio.
