### ISSUE TITLE
Iso-surface extraction does not work correctly

### ISSUE THREAD

**Issue by hoangthaiduong** [sci-visus/visus-issues#325]
The iso-surface appears at a corner of the volume. Please refer to the screenshot below:

![isosurface-bug](https://cloud.githubusercontent.com/assets/8607075/7877124/b665048c-058a-11e5-8d18-4d754bf15820.png)

This bug starts appearing in the following commit
fabd338962b938d6d5a31f930f1b821a224b62e0

**Comment by scrgiorgio** [comment]
https://github.com/sci-visus/nvisusio/commit/8202789d9b88452839e53556f722341ace7e88db

**Comment by hoangthaiduong** [comment]
solved. thank you :)
