### ISSUE TITLE
very distracting moire pattern when raycasting anisotropic volumes

### ISSUE THREAD

**Issue by cchriste** [sci-visus/visus-issues#327]
Even with highest quality, bspline filtering, and pre-integration, this moire pattern is very distracting.

![screenshot 2015-06-09 11 45 08](https://cloud.githubusercontent.com/assets/1260945/8064295/61da00e8-0e9f-11e5-82cf-8fbab90cb56d.png)

The volume can be found here: http://pcmdi11.llnl.gov:8080/mod_visus?dataset=acme-test.ORNL.HIGHRES.init.all.v1-lon_lat_lev_time

**Comment by cchriste** [comment]
This is maaaaybe related to #349

**Comment by scrgiorgio** [comment]
This issue was moved to sci-visus/nvisusio#468
