### ISSUE TITLE
installers for visus

### ISSUE THREAD

**Issue by cchriste** [sci-visus/visus-issues#329]
**Needs to:**

1) install binaries
2) offer to add visus tools to path
3) install python library
4) create ~/.visus directory for cache and config
5) create app association to visus viewer when a midx/idx file is selected

**Possible installers:**

*Windows:*
http://nsis.sourceforge.net/Main_Page
http://wixtoolset.org/

*OSX:*
http://stackoverflow.com/questions/11487596/making-os-x-installer-packages-like-a-pro-xcode4-developer-id-mountain-lion-re

*Linux:*
Ask Ali

**Comment by scrgiorgio** [comment]
This issue was moved to sci-visus/nvisusio#466
