### ISSUE TITLE
add ability to load visus.config from within viewer

### ISSUE THREAD

**Issue by cchriste** [sci-visus/visus-issues#331]
With on-demand conversion, users download a new visus.config and they have reported confusion because they try to load the file after starting the viewer.

This functionality could be supported since it is the same as "reload config" just with a user-specified config.

**Comment by cchriste** [comment]
Make priority HIGH because this is important for ViSOAR at SH-EAHE workshop.

**Comment by cchriste** [comment]
Resolved by pull request #421

**Comment by cchriste** [comment]
It works by appending the new config's children to the currently loaded config, then loading the first dataset in the new config. This is the most sensible behavior for someone who simply downloads the config from the web (e.g. for ondemand climate data). 

Note: the new config is not merged with the original on disk, only in memory. Not sure if this should be the behavior, but It seems reasonable.

**Comment by cchriste** [comment]
Still not sure about merging the new config with the existing config on disk (so you don't have to open it every time you want to view that particular data). Maybe we should have a "merge config" menu option? 

I'm assigning this to @scrgiorgio for his opinion. Giorgio, you can load any visus.config using file->open and it will append that config's bookmarks to your own for the current session only.

What do you think about:
 1) a merge/import config menu option
 2) automatically merging newly opened config with user's config on disk
 3) never merging opened config with user's config

**Comment by scrgiorgio** [comment]
This issue was moved to sci-visus/nvisusio#470
