### ISSUE TITLE
mod_visus look for visus.config in $HOME prior to loading system default 

### ISSUE THREAD

**Issue by cchriste** [sci-visus/visus-issues#332]
Now that we are creating shared installations of mod_visus on supercomputers we must enable the ability for users to provide their own visus.config.

**Comment by hoangthaiduong** [comment]
So will this $HOME directory depend on whoever starts the mod_visus process?
But if I'm not wrong, there could only be one process listening on one port, so what does "shared installations of mod_visus" mean in this case?

**Comment by cchriste** [comment]
One process per port *per node*. The typical scenario on shared resource machines is that the user will invoke a job that acquires a node and start the server on this node. 

Ssh tunneling can be used if the node does not provide a publicly accessible IP.
 
The user who starts the server will be the one whose config is loaded.

**Comment by cchriste** [comment]
This is fixed with https://github.com/sci-visus/nvisusio/pull/396
