### ISSUE TITLE
palette connection lost

### ISSUE THREAD

**Issue by pascucci** [sci-visus/visus-issues#335]
If I move a palette to the top to be shared among multiple nodes (and remove the other ones) the proper connections among the palettes are not created. 
The original palette is still connected to just one note
The ones that are removed leave behind an orphan rendering note with no input palette.

**Comment by cchriste** [comment]
Confirmed this is still an issue.

**Comment by scrgiorgio** [comment]
This issue was moved to sci-visus/nvisusio#465
