### ISSUE TITLE
add tooltips (hover mouse to view)

### ISSUE THREAD

**Issue by cchriste** [sci-visus/visus-issues#337]
The new ui really needs some tooltips to identify the operation of individual elements.

**Comment by cchriste** [comment]
(assigned to Amy for now, but this may be a task for Giorgio)

**Comment by amygooch** [comment]
I was surprised this one wasn't on the issues.. must have been part of
another forum we had for organizing ourselves.

 Valerio asked me about this long ago and I looked into it.. it is part of
JUCE, but not exposed in ViSUS right now.. I think if Giorgio can help
making the JUCE hooks available, I'll go thru and put them in the tools.

On Tue, Sep 8, 2015 at 4:16 PM, Cameron Christensen <
notifications@github.com> wrote:

> (assigned to Amy for now, but this may be a task for Giorgio)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sci-visus/visus-issues/issues/337#issuecomment-138702750>
> .
>



-- 

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Dr. Amy Ashurst Gooch          http://www.sci.utah.edu/people/agooch.html
<http://www.csc.uvic.ca/~agooch>
Research Scientist                                          amy.a.gooch at
gmail.com
Scientific Computing and Imaging                          agooch at
sci.utah.edu
University of Utah

(801)-828-5038
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

**Comment by scrgiorgio** [comment]
I think I'm already exposing it with "onmouseenter/onmouseexit" (see Component class).
if it's not working please debug the following Visus/Juce function:

virtual void mouseEnter(const juce::MouseEvent& e) CPP11_OVERRIDE

(FILE visus_gui_juce.h line 261)

**Comment by cchriste** [comment]
Assigning to Amy.

**Comment by scrgiorgio** [comment]
This issue was moved to sci-visus/nvisusio#464
