### ISSUE TITLE
Reset observed while compiling RenderMeshGPUNormals shader

### ISSUE THREAD

**Issue by anikethvenkat** [sci-visus/visus-issues#339]
Issue Description:

- Switch to Toolbar UI —> OpenMultipleFiles and load default files (Fred000-003)
- Goto xxx and select isocontour

Observation:
- Resets while compiling the RenderMeshGPUNormals shader

![shader reset](https://cloud.githubusercontent.com/assets/13954719/9791845/5d22cca8-579a-11e5-8807-eb51e0a1d45c.png)

**Comment by cchriste** [comment]
Aniketh,
Let's sit down to code review your changes and submit a pull request for
the fixes.
Best,
Cameron

**Comment by scrgiorgio** [comment]
Yes Cameron is right,
and about visus_rendermesh Duong must me in the loop.
Ciao,Giorgio.

2015-09-14 19:03 GMT+02:00 Cameron Christensen <notifications@github.com>:

**Comment by cchriste** [comment]
Duong, would you mind code reviewing this with Aniketh? He already
understands github forks, rebase, etc.
Thanks!

**Comment by hoangthaiduong** [comment]
Yes I'm happy to. Can we do the code review on either Tuesday/Thursday/Friday afternoon?

**Comment by anikethvenkat** [comment]
Issued fixed with Commit: c2217d636b836bbc3cda2fa093b11bf948e50fb3.
