### ISSUE TITLE
Reset observed while showing the tree in OpenMultipleUrlViews

### ISSUE THREAD

**Issue by anikethvenkat** [sci-visus/visus-issues#340]
Issue Description:
- Switch to Toolbar UI —> OpenMultipleFiles and load default files (Fred000-003)
- Repeat Step 1 until you observe a reset (usually resets within a couple of trials)

Observation:
- Resets while showing the tree

![repeat_openmultilefiles_usecase_multiple_times](https://cloud.githubusercontent.com/assets/13954719/9791929/c6a43f18-579a-11e5-979a-27790c34f943.png)

**Comment by anikethvenkat** [comment]
Can we close this also with your new openMultiFile interface?

**Comment by scrgiorgio** [comment]
yes, closing it
