### ISSUE TITLE
OpenMultipleUrlViews needs to be re-written to support clear screen

### ISSUE THREAD

**Issue by anikethvenkat** [sci-visus/visus-issues#341]
Issue Description:
- Switch to Toolbar UI —> OpenMultipleFiles and load default files (Fred000-013)
- Once the volume is loaded, repeat step 1 and load Fred000-003

Observation:
- GUI gets stuck waiting on a semaphore (happens while clearing the screen => removing the model)

![infinite_semaphore_wait](https://cloud.githubusercontent.com/assets/13954719/9791981/11ae02c8-579b-11e5-96af-eff1666d7d31.png)

**Comment by cchriste** [comment]
Giorgio, we really need a "clear screen" function. I spent some time trying
to reset the viewer model inside the openmultipleurls function, but it is
too draconian and destroys the dialog right out from under me! The existing
code tries to do dataflow surgery, but this seems too hard. We just need a
reset function.

**Comment by scrgiorgio** [comment]
"Clear screen"=="File/New"?

2015-09-14 19:06 GMT+02:00 Cameron Christensen <notifications@github.com>:

**Comment by cchriste** [comment]
Yes.
Right now that happens when there is no parent passed to openFile or
openUrl.

**Comment by scrgiorgio** [comment]
Try now https://github.com/sci-visus/nvisusio/commit/96face040de35acb9b6987a95fee8433a24542b8

(btw the experimental part need to be fixed. The separation between model/view code is broken)

**Comment by cchriste** [comment]
Still crashes for me, after retrying the default action of "Open Multiple Files" four times:

```
10:48:17.8527 INFO DB_QUERYNODE.74 Query msec(891) level(0/4/17/30) dims(64 64 32 1 1) dtype(uint16) filter(nullptr) access(nullptr) url(http://atlantis.sci.utah.edu/mod_visus?action=readdataset&cache=1&dataset=Fred002) 
^C
Program received signal SIGINT, Interrupt.
0x00007fff959dda56 in semaphore_wait_trap ()
(gdb) where
#0  0x00007fff959dda56 in semaphore_wait_trap ()
#1  0x00007fff94e619f9 in _dispatch_semaphore_wait_slow ()
#2  0x00000001004b233c in Visus::Semaphore::down ()
#3  0x0000000100498ccc in Visus::ThreadPool::joinProcessing ()
#4  0x00000001003c633d in Visus::Dataflow::dropProcessing ()
#5  0x00000001003c8e9a in Visus::Dataflow::removeNode ()
#6  0x00000001003c8d3e in Visus::Dataflow::removeNode ()
#7  0x00000001001fc364 in Visus::ViewerWindow::openFile ()
#8  0x000000010021a49f in Visus::ViewerWindowActions::OpenFile::runAction ()
#9  0x0000000100206353 in Visus::ViewerWindow::runAction ()
#10 0x0000000100231140 in Visus::Experimental::OpenMultipleUrlsView::onOpenMultipleURL ()
#11 0x0000000100212f1c in Visus::Signal<Visus::Void>::emitSignal ()
#12 0x00000001004291cd in Visus::FlatButton::onMouseUp ()
#13 0x0000000100432e80 in non-virtual thunk to Visus::CreateJuceClass<Visus::Label, juce::Label>::mouseUp(juce::MouseEvent const&) ()
#14 0x0000000100aafaac in juce::Component::internalMouseUp ()
#15 0x0000000100b6d5f8 in juce::MouseInputSourceInternal::sendMouseUp ()
#16 0x0000000100b6d3d8 in juce::MouseInputSourceInternal::setButtons ()
#17 0x0000000100b54bcc in juce::MouseInputSourceInternal::handleEvent ()
#18 0x0000000100b45513 in juce::ComponentPeer::handleMouseEvent ()
#19 0x0000000100b71524 in juce::NSViewComponentPeer::sendMouseEvent ()
#20 0x0000000100b6f323 in juce::JuceNSViewClass::mouseUp ()
#21 0x00007fff8fed2145 in -[NSWindow sendEvent:] ()
#22 0x00007fff8fe735d4 in -[NSApplication sendEvent:] ()
#23 0x00007fff8fcc39f9 in -[NSApplication run] ()
#24 0x0000000100a3e65c in juce::JUCEApplicationBase::main ()
#25 0x0000000100a3e553 in juce::JUCEApplicationBase::main ()
#26 0x000000010000712a in main ()
(gdb) 
```

**Comment by scrgiorgio** [comment]
Ok cannot replicate on windows.
Need to debug it in on OSX

**Comment by scrgiorgio** [comment]
Tried on OSX. After 10 times of "Open multiple files" (with the defaults, Fred 000 to 003) it still works.

Can you do a full debug on your side and try to discover what's going on?
(Maybe Amy could help us just running and telling if she has a crash)

**Comment by cchriste** [comment]
I cannot get this to crash anymore. Closing the issue until it is seen
again.
