### ISSUE TITLE
Clipping does not work when multiple files are loaded

### ISSUE THREAD

**Issue by anikethvenkat** [sci-visus/visus-issues#343]
Issue Description:
- Switch to Toolbar UI —> OpenMultipleFiles and load default files (Fred000-003)
- Once the volume is loaded, zoom-in and refresh data.
- After refresh, zoom back

Observation:
- Volumes that do not overlap the camera are also rendered.

![multi_volume_clipping](https://cloud.githubusercontent.com/assets/13954719/9868338/bdd17a02-5b34-11e5-9703-ee530d04ea79.png)

**Comment by anikethvenkat** [comment]
Hi Giorgio,

Please assign this issue to me.. I will be pushing a fix for the same tomorrow.

Thanks,
Aniketh

**Comment by scrgiorgio** [comment]
Assigned to you (now you are a member of visus-issue)

**Comment by anikethvenkat** [comment]
Issue fixed with Commit: 827142840b8e8709946a6efc1f0f5e8478a67b79.
