### ISSUE TITLE
fix addDataset function of mod_visus to handle multi-threaded apache/httpd

### ISSUE THREAD

**Issue by cchriste** [sci-visus/visus-issues#344]
Apache/httpd always starts multiple, non-interacting processes, regardless of its configuration (some configs allow for one process, but eventually start more as server demand increases).

We need a way for the addDataset function of mod_visus to communicate with the other running server processes to ensure that datasets will be available from all processes. 

Currently, if a user adds a datasets using this function, the dataset will only show up for one of the existing server processes.

Using a database such as sqlite and having the servers each poll for updates has been proposed as a solution (see conversation in #mod_visus channel on slack).

**Comment by scrgiorgio** [comment]
What about a Thread that watch the visus.config and in case it changes, then it reloads the datasets?
Like the file web.config for IIS

**Comment by cchriste** [comment]
Something must take care not to read a partially written version.

For example, thread A receives addDataset command, starts to write new
config.
Meanwhile, thread B reads incompletely written config, which is corrupt.

Will our .lock files suffice for this?

**Comment by scrgiorgio** [comment]
Yes a FileLock should work. Before reading/writing visus.config the
mod_visus should acquire the FileLock (like we are doing for visusconvert
--fix-range)

2015-09-16 18:12 GMT+02:00 Cameron Christensen <notifications@github.com>:

**Comment by scrgiorgio** [comment]
2015-09-16 18:15 GMT+02:00 Giorgio Scorzelli <scrgiorgio@gmail.com>:

**Comment by cchriste** [comment]
It sounds like it will work... please try it!

**Comment by cchriste** [comment]
As we discussed: when a dataset can't be found, check the timestamp of the latest config and reload it if newer. To make the reload fast, only read the config and call adddataset only on the datasets this server doesn't already have in its existing config.

**Comment by anikethvenkat** [comment]
Possible solution:
- check timestamp of visusconfig in memory (@giorgio: Is there anything available in Visus to do this? )
```
 if (not newer) 
   {
     return "NetResponseError(HttpStatus::STATUS_NOT_FOUND,"Cannot find dataset(" + dataset_name + ")");"
   }
else 
   { 
    StringTree* visus_config=Application::getCurrent()->getConfig();
    std::vector<StringTree*> configs = visus_config ->findAllChildsWithName("dataset", true);
    String visus_config_filename=Application::getCurrent()->getConfigFilename();
    StringTree new_visus_config;
    bool bEnablePostProcessing=false;
    if (!XmlEncoder().decode(new_visus_config,Application::getCurrent()-   >loadTextDocument(visus_config_filename),bEnablePostProcessing))
    {
      VisusWarning()<<"Cannot load visus.config";
      VisusAssert(false);//TODO rollback 
      return false;
    }
    std::vector<StringTree*> new_configs = new_visus_config.findAllChildsWithName("dataset", true);
    std::sort(configs.begin(), configs.end());
    std::sort(new_configs.begin(), new_configs.end());
    std::vector<StringTree*> dataset;
    std::set_intersection(configs.begin(), configs.end(),
                          new_configs.begin(), new_configs.end(),
                          std::back_inserter(dataset));
    datasets->addPublicDataset(dataset,false);
    }
```

**Comment by scrgiorgio** [comment]
I don't think you can use StringTree* for comparison... maybe the unique
name with an ad-hoc compared?

2015-10-02 19:21 GMT-06:00 anikethvenkat <notifications@github.com>:

**Comment by cchriste** [comment]
Pretty clever, but I think you'll need an operator that sorts based on the
value of the _alias_ attribute of the dataset. Also, if it's a set you
don't have to sort.

A more "manual" way to do the same thing would be to walk the elements of
the new config and find them in the old, adding them if they don't already
exist.

One item that we might consider revising: currently _alias_ must be unique,
even between groups. It may be better for groups to act as a namespace so
datasets would be referenced using group+alias (e.g. Microscopy/MM358/000
for a datasets called _000_ in a sub-group called _MM358_ in a group called
_Microscopy_).
