### ISSUE TITLE
underlay the histogram of the data with the palette curves

### ISSUE THREAD

**Issue by cchriste** [sci-visus/visus-issues#347]
This is similar to #345.

The user of the palette is essentially running blind when she changes the existing curves because the histogram of the data is not displayed. Instead, she must experimentally change the palette, watching the data appear and disappear int he volume. This trial-and-error approach is tedious and has a likelihood of missing important data that would be obvious were a histogram to be displayed directly with the curves.

For palettes that serve multiple volumes, either not showing the data or showing the union of the data would be acceptable solutions.

For the more typical case, this feature would make the palette much superior to its current state.

**Comment by cchriste** [comment]
Something like this: 

![screen shot 2015-09-15 at 4 31 40 pm](https://cloud.githubusercontent.com/assets/1260945/9891932/64a44084-5bc7-11e5-88da-4b18c74291a9.png)

**Comment by amygooch** [comment]
Have you seen the latest New UI palette editor for ViSUSViewer?

(see attached)

its not perfect, but I was getting toward the same point.
This is part of develop

Amy


On Tue, Sep 15, 2015 at 5:33 PM, Cameron Christensen <
notifications@github.com> wrote:

> Something like this:
>
> [image: screen shot 2015-09-15 at 4 31 40 pm]
> <https://cloud.githubusercontent.com/assets/1260945/9891932/64a44084-5bc7-11e5-88da-4b18c74291a9.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sci-visus/visus-issues/issues/347#issuecomment-140566330>
> .
>



-- 

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Dr. Amy Ashurst Gooch          http://www.sci.utah.edu/people/agooch.html
<http://www.csc.uvic.ca/~agooch>
Research Scientist                                          amy.a.gooch at
gmail.com
Scientific Computing and Imaging                          agooch at
sci.utah.edu
University of Utah

(801)-828-5038
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

**Comment by amygooch** [comment]
darn, here is the right image ;)[image: Inline image 1]

On Tue, Sep 15, 2015 at 6:19 PM, Amy Gooch <agooch@sci.utah.edu> wrote:

> Have you seen the latest New UI palette editor for ViSUSViewer?
>
> (see attached)
>
> its not perfect, but I was getting toward the same point.
> This is part of develop
>
> Amy
>
>
> On Tue, Sep 15, 2015 at 5:33 PM, Cameron Christensen <
> notifications@github.com> wrote:
>
>> Something like this:
>>
>> [image: screen shot 2015-09-15 at 4 31 40 pm]
>> <https://cloud.githubusercontent.com/assets/1260945/9891932/64a44084-5bc7-11e5-88da-4b18c74291a9.png>
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/sci-visus/visus-issues/issues/347#issuecomment-140566330>
>> .
>>
>
>
>
> --
>
> ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> Dr. Amy Ashurst Gooch          http://www.sci.utah.edu/people/agooch.html
> <http://www.csc.uvic.ca/~agooch>
> Research Scientist                                          amy.a.gooch at
> gmail.com
> Scientific Computing and Imaging                          agooch at
> sci.utah.edu
> University of Utah
>
> (801)-828-5038
> ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>



-- 

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Dr. Amy Ashurst Gooch          http://www.sci.utah.edu/people/agooch.html
<http://www.csc.uvic.ca/~agooch>
Research Scientist                                          amy.a.gooch at
gmail.com
Scientific Computing and Imaging                          agooch at
sci.utah.edu
University of Utah

(801)-828-5038
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

**Comment by amygooch** [comment]
![screen shot 2015-08-21 at 9 30 09 am](https://cloud.githubusercontent.com/assets/1149305/9892669/a50f98d0-5bd6-11e5-902f-f1f0f6950214.png)

**Comment by scrgiorgio** [comment]
cameron is Amy experimental solution enough?

**Comment by cchriste** [comment]
Yes.

**Comment by scrgiorgio** [comment]
Ok so I think you are in charge of closing this issue.

BTW looking at the experimental source code, I think that the Palette+Histogram joined view works well only if we had only one QueryNode in the scenegraph. Amy, am I right? I see:

Node*  stats_selection =this->window->getModel()->findNodeRecursively<QueryNode>(this->window->getModel()->getRoot());

**Comment by cchriste** [comment]
Related to this, when can we push to unify the GUI? I don't think we'll
ever finish the so-called experimental gui until we start using it
exclusively.

**Comment by cchriste** [comment]
I give up. Closing this issue.
