### ISSUE TITLE
slice-based renderer opacity should not vary with number of slices

### ISSUE THREAD

**Issue by cchriste** [sci-visus/visus-issues#348]
When interacting, the number of slices is reduced to permits faster rendering. 
When stopped, the number of slices is increased to create a higher-quality image.
However, when stopped, the image becomes very opaque due to incorrect weighting of the slice opacity.

This behavior can also be seen by manually changing the number of slices.

The following two images show the rendering while panning (more transparent) and while stopped (more opaque).

![screenshot 2015-09-15 23 22 21](https://cloud.githubusercontent.com/assets/1260945/9897014/ac5c65f8-5c00-11e5-87ed-623c08cdb474.png)
![screenshot 2015-09-15 23 21 11](https://cloud.githubusercontent.com/assets/1260945/9897013/ac5b703a-5c00-11e5-8575-3a5c9b4c18dd.png)

**Comment by scrgiorgio** [comment]
This issue was moved to sci-visus/nvisusio#460
