### ISSUE TITLE
Progress on ViSOAR image updating

### ISSUE THREAD

**Issue by amygooch** [sci-visus/visus-issues#353]
I think a necessary feature for ViSOAR would be a little animation or something that shows that the view data is still coming in... The user should be informed that the view is still in progress... My Sony TV does this to let me know it is still trying to find Netflix.

**Comment by amygooch** [comment]
Added in my branch, will be merged

**Comment by cchriste** [comment]
Assigning to @amygooch to revisit, close if resolved.

**Comment by scrgiorgio** [comment]
This issue was moved to sci-visus/nvisusio#459
