### ISSUE TITLE
JTreeRender not properly scaled, only draws gray spheres

### ISSUE THREAD

**Issue by cchriste** [sci-visus/visus-issues#356]
![screenshot 2015-09-29 09 51 55](https://cloud.githubusercontent.com/assets/1260945/10169767/d93e2d38-668f-11e5-8278-23a9375139cc.png)

**Comment by cchriste** [comment]
Also, nodes are no longer colored properly (both color by component and color by type are just drawing gray nodes).

![screenshot 2015-09-29 09 56 16](https://cloud.githubusercontent.com/assets/1260945/10169880/583c7a40-6690-11e5-8798-532f8c6f3d54.png)

**Comment by cchriste** [comment]
More on the coloring: colors are all missing because spheres are drawn with front and back face materials mixed up. Here is an image generated by setting back face colors for min/max/saddle.

However color by component is no longer working: just colors everything the same.

![screenshot 2015-09-29 09 59 40](https://cloud.githubusercontent.com/assets/1260945/10170306/8168005a-6691-11e5-8057-bbea068317df.png)

**Comment by scrgiorgio** [comment]
This issue was moved to sci-visus/nvisusio#456
