### ISSUE TITLE
--create (formerly --auto) no longer works

### ISSUE THREAD

**Issue by cchriste** [sci-visus/visus-issues#357]
--create (formerly --auto) no longer works after recent visusconvert update:
```
# ---------------------------------------------------
# For very simple conversions, all you need is --create
# --------------------------------------------------
$CONVERT --import $RESOURCES/tutorials/cat_gray.tga --create temp/cat_gray.idx 
$CONVERT --import $RESOURCES/tutorials/cat_rgb.tga  --create temp/cat_rgb.idx 
```

In the cases above, doesn't create anything (but reports success like it did). When importing from an idx, it creates the .idx and says it writes the data but nothing is written.

**Comment by cchriste** [comment]
This is the problematic commit: https://github.com/sci-visus/nvisusio/commit/8c5a45094f145ed331761344aa4fe0b8cf66309d

**Comment by scrgiorgio** [comment]
Fixed: https://github.com/sci-visus/nvisusio/commit/89aeb2c5ecf7df4c4a8439f35f42f25f57f3e397

**Comment by cchriste** [comment]
Confirmed this is fixed.
