### ISSUE TITLE
2D Ray Cast

### ISSUE THREAD

**Issue by pavolzetor** [sci-visus/visus-issues#359]
2D ray cast does not compile because of OSX fix.

in file visus_renderarraynode.glsl
vec3 texcoord=v_texcoord; //quell compiler error on OSX

However, it seems to be the case that the 2D ray cast is not used anyway. The possible solutions are:
a) remove the code
b) fix the code and use it

Cameron's comment:
I strongly suggest we fix the code and use it. The reason is that "2D" is not necessarily without thickness, and sometimes "2D" arrays result from higher-dimensional queries (e.g. progression of two levels for a bitstring of 012012 and logical resolution [x,y,2]).

The other consideration is that some users (Uintah) define their domains on the "node" level, the corners of the cell, rather than the "cell" level, the center of a voxel.

Finally, it would also behoove us to support 2D geometry such as meshes in the raycaster. Even if the dataflow to import this geometry must be constructed manually (like the existing point cloud renderer), it is desirable for numerous applications, such as microscopy.

**Comment by scrgiorgio** [comment]
This issue was moved to sci-visus/nvisusio#457
