### ISSUE TITLE
CalloutBox for Inputs from user 

### ISSUE THREAD

**Issue by amygooch** [sci-visus/visus-issues#360]
Due to delivering ViSOAR on App Store, we need to switch the user input to pop up screens (like listing a file to open, showing bookmarks, unlocking bookmark, etc. and probably the color picker (which Apple didn't seem to catch).

Currently this is Dialogs::InputBox in the ViSUS Framework

What we need is similar to the iOS popup view (like http://i.stack.imgur.com/twyMS.png), or juce::CalloutBox. I couldn't find a straight forward way of using juce::CalloutBox. I think we need to grow something that uses it.

Although it is kind of frustrating to try to cater to Apple's whim, it does make sense that the controls stay close to where the user to pressed for the purposes of continuity.

**Comment by amygooch** [comment]
Cameron replied to this: 
I'd like to understand this better. Consider dialogs that show immediate
results on screen, such as the filters an color picker. We would never want
these to be pop ups (aside from the current desktop version). There also
seems to be ample precedent for embedded controls like this. For bookmarks
I can see us in a pop up, but not for color chooser and filters.

Cameron

**Comment by amygooch** [comment]
Apple on this subject:

“In general, consider creating a modal context only when:
It’s critical to get the user’s attention 
A self-contained task must be completed—or explicitly abandoned—to avoid leaving the user’s data in an ambiguous state”

So options like, pop up for loading a file, loading a bookmark list to select input, change or accept file name for session save, load bookmark from new file, etc. are appropriate as I read this (and we must have the calloutbox context, with an arrow to the button that initiated the action).

Interactive things like changing settings on a slider should be in the "toolbar" (for ViSOAR)..

More complex options like Color picker, Transfer function, etc. where the UI is more than a slider and takes up actual screen space AND they probably require iteration (ie make a change, see preview, repeat) are much tricker to judge and must be delt with individually.

A pop over [According to Apple*] can NOT be used for this: "Make sure people can use a popover without seeing the app content behind it. " So in fact, I probably should just make the color picker simpler and put it IN the toolbar for ViSOAR, like I did with the Transfer function for ViSUSViewer.

Thinking through all of these things is making me make choices for the iPAD apps.. like "Load from file" is probably not highly likely and thus probably shouldn't be on the store (unless a client needs it). Where as "Load from URL" makes sense. However, "load from session" and "save session" do make sense

Thus, File menu is now:
Load from URL, load session, load from Bookmarks, unlock bookmarks, load new bookmarks, save session.

Note: Load session will have to be redone and specialized for iPad.. Apple just loads them as a list (there is only one place to look for such things)

*https://developer.apple.com/library/ios/documentation/UserExperience/Conceptual/MobileHIG/ContentViews.html#//apple_ref/doc/uid/TP40006556-CH13-SW1

**Comment by amygooch** [comment]
The upshot of this is that I'd like some help architecting the use of CalloutBox to hold things we've used Dialogs::InputBox for in the past (ie in ViSOAR, when user types in file to load)

**Comment by cchriste** [comment]
Assigning back to @amygooch to decide what to do.

**Comment by scrgiorgio** [comment]
This issue was moved to sci-visus/nvisusio#454
