### ISSUE TITLE
ViSUS download speed

### ISSUE THREAD

**Issue by hoangthaiduong** [sci-visus/visus-issues#363]
Contrary to uninformed assumptions by some of us, all of ViSUS’s network activities happen on one thread, always. The thread in question runs an infinite loop over a queue to find and execute any active network requests (see function `NetPool::entryProc()` in `visus_netpool.cpp`). ViSUS uses two different ways to download volume data from the network, depending on whether caching is enabled.

# Caching disabled
When there is no caching, only one TCP connection is made (per HZ level). I confirmed this behavior using Wireshark. The problem with using only one TCP connection is that various factors (TCP buffer size, congestion control, server’s settings, etc) can cause the connection to not ultilize the full bandwith. We observed this many times, where ViSUS would download at 50% or even 5% of the network’s maximum speed.

# Caching enabled
When caching is enabled, ViSUS issues one network request for each IDX block. These requests are put into a queue, and are later picked up from the queue and submitted to the cURL library, which will then group the requests into a (fewer) number of TCP connections. See the file `visus_netpool.cpp`. Since multiple TCP connections are made at the same time (by one thread), this approach can achieve a better speed than the previous one.

Unfortunately the thread that submits network requests is also responsible for performing follow-up computations on the downloaded data (decoding, merging, encoding, writing to disks, etc). This is bad because the thread will not be able to come back and service new network requests fast enough to saturate a high-bandwidth network.

I ran a profiling session using ViSUS to download 2 MB of data (2kbit1) from `atlantis` to my home laptop. It took about 6 seconds to finish downloading and rendering the volume. Most of the time was spent in the `NetPool::perform()` function, specifically in the call to `ModVisusAccess::onNetJobDone()`. This confirms that the post-processing time dominates the network download time (see the screenshot below).

![screenshot - 12_1_2016 5_38_11 pm](https://cloud.githubusercontent.com/assets/8607075/12281818/89cc4996-b956-11e5-99cc-9949e73220b8.png)

Monitoring the network with Wireshark, I noticed that there were 260 TCP packets transferred, of which on average only 7 were in-flight together at any given time. The average size of a packet is 8.7 KB, and the average transfer duration of a packet is 0.14 s. These amount to a transfer speed of about 435 KB/s, which is far below the maximum bandwidth of my home connection (about 2 MB/s). The low average number of concurrent packets suggests that network requests weren’t submitted fast enough.

# Solution
I propose separating the post-processing code (`ModVisusAccess::onNetJobDone`) to another thread so that network requests can be executed continuously without having to wait for post-processing of downloaded data to complete. Alternatively, we can investigate using asynchronous network and disk I/O libraries (Boost Asio or libuv) to achieve a better overlapping of computation and I/O.

**Comment by scrgiorgio** [comment]
ok I need to work on this

2016-01-13 2:04 GMT+01:00 hoangthaiduong <notifications@github.com>:

**Comment by cchriste** [comment]
Duong and I were able to enable a significant speedup by performing caching in a separate thread. Here is our code (using c++11 for expedience). Note that the speedup is not enough: we still probably need to bundle block requests for larger network transfers. Further, the differences observed vary depending on whether or not the data is compressed, since compressed data (e.g. 2kbit1) may contain many 0-regions and therefore send many tiny blocks -> extremely inefficient. 

Transfer rates for a single thread or non-block query access are not affected by this change, and are still terrible.

```
        //write on up accesses (if allowed)... i don't care if it fails
        if (can_write)
        {
          std::vector< SharedPtr<Access> > childs_local(childs);
          SharedPtr<BlockQuery>            master_local=master;
          auto index_local=this->index;
          Dataset *dataset_local=getDataset();
          std::thread([index_local,childs_local,dataset_local,master_local](){
              for (int J=index_local-1;J>=0;J--) 
              {
                if (childs_local[J]->can_write)
                {
                  SharedPtr<BlockQuery> write(new BlockQuery(dataset_local,'w'));
                  write->aborted      =master_local->aborted;
                  write->setTime(master_local->getTime());
                  write->setField(master_local->getField());
                  write->setStartAddress(master_local->getStartAddress());
                  write->setEndAddress(master_local->getEndAddress());
                  write->setAccess(childs_local[J].get());
                  write->begin();
                  write->setBuffer(master_local->getBuffer());
                  BlockQuery::execute(write); //NOTE: I'm not waiting for the completition here! don't know if this the perfect solution...
                }
              }
            }).detach();
        }
        BlockQuery::setDone(master,QueryOk);
      }
```

**Comment by cchriste** [comment]
Here are results for a test of block size, which seems to make a huge difference in transfer speed, further supporting the hypothesis that many small transfers are extremely inefficient and causing our network transfer rates (and others like from disk or memory?) to be very slow. This graph summarizes the results. Note that changes blocks_per_file does not seem to affect transfer rate (see the two 16bpb examples). Large blocks result in much (>10X) better network bandwidth utilization.

![block_size_transfer_rate_comparison](https://cloud.githubusercontent.com/assets/1260945/12852198/058a32b8-cbeb-11e5-8735-990a421e91af.png)

**Comment by scrgiorgio** [comment]
Do you have a script to test it by myself?

btw your test confirms a very know issue: the best transfer rate is when
you dowload a huge self-contained-file (thus minimizing the ping-pong
effect of the HTTP response-reply overlay).

Maybe we can group several request in a Network layer...
I was studying Chrome code and they are using a second process for
network-requests. But they are not grouping requests (it would cause
enourmous problems in case a Web Server is really a cloud with load
balancing).

Their tile-size is pretty much what we normally use (think about Google
maps: is like suggesting that the perfect size for a Google tile sholud be
.4096x4094==24bpb... and this is wrong!).

Are we sure that the speedness *is not a problem of the Visus server*
(==incoming request waiting to be served)?



2016-02-05 17:31 GMT+01:00 Cameron Christensen <notifications@github.com>:

**Comment by scrgiorgio** [comment]
This issue was moved to sci-visus/nvisusio#453
