### ISSUE TITLE
original file bounding box still shown after transfrom

### ISSUE THREAD

**Issue by cchriste** [sci-visus/visus-issues#364]
The transform should modify the original bounding box and only the result should be shown. The original box is no longer relevant to the user.

![screenshot 2016-03-05 11 14 02](https://cloud.githubusercontent.com/assets/1260945/13549509/b2f8f256-e2c3-11e5-9f27-a25b7c5300ef.png)

**Comment by scrgiorgio** [comment]
This issue was moved to sci-visus/nvisusio#458
