### ISSUE TITLE
impossible to grab manipulator

### ISSUE THREAD

**Issue by cchriste** [sci-visus/visus-issues#365]
In this situation, zoomed close to the volume, it is impossible to grab the manipulator with the mouse (not just the scale manipulator, which is hidden off screen, but also the translate manip which can be seen but not used).
![screenshot 2016-03-05 11 20 43](https://cloud.githubusercontent.com/assets/1260945/13549544/90b75704-e2c4-11e5-974a-a5c190014a20.png)

**Comment by scrgiorgio** [comment]
This issue was moved to sci-visus/nvisusio#452
