### ISSUE TITLE
add ability to use <access> for midx ensemble members

### ISSUE THREAD

**Issue by cchriste** [sci-visus/visus-issues#366]
It seems our current midx "MultipleAccess" does not support using access for the individual members. This prohibits utilizing midx to enable server-side computation of on-demand datasets, as well as the ability to cache remote ensemble members.

```
<!-- this never calls ondemand, only returns data that already exists on disk --> 
<dataset typename="IdxMultipleDataset">
        <dataset name="A" permissions="public" url="file:///ondemand/A.idx">
                <access name="Multiplex" type="multiplex">
                        <access chmod="r" type="disk" />
                        <access chmod="r" ondemand="external" path="http://localhost:42299/convert" type="ondemandaccess" />
                        <access chmod="r" type="disk" />
                </access>
        </dataset>
</dataset>
```
```
<!-- this doesn't create a cache on the server, only returns data from remote server -->
<dataset typename="IdxMultipleDataset">
        <dataset name="B" permissions="public" url="http:///atlantis.sci.utah.edu/mod_visus?dataset=2kbit1">
                <access name="Multiplex" type="multiplex">
                        <access chmod="rw" type="disk" url="file:///$(VisusCacheDirectory)/2kbit1/visus.idx" />
                        <access chmod="r" type="network" compression="zip" />
                </access>
        </dataset>
</dataset>
```

**Comment by scrgiorgio** [comment]
I think it's only a problem of syntax.
Don't confuse "Multiplex" (which is something we are using for any dataset, not only MIDX) with "MultipleAccess" (this is what you want).

Example of my visus.config:

<dataset name="NameOfMyMIDX" url="path/to/somewhere/visus.midx">
    <access name="MultipleAccess" type="MultipleAccess">
      <access name="FirstDatasetName"  type='whatever'>...</access>
      <access name="SecondDatasetName" type='whatever'>...</access>
    </access>	
</dataset>

(NOTE: Be careful: the inner dataset names must match)

Let me know

**Comment by cchriste** [comment]
I'm trying to use this on the server, where on-demand conversion is enabled. Your example seems to only be working for the client side. 

Here is what I have _on the server_.

```ondemand.midx

**Comment by cchriste** [comment]
I'm trying to use this on the server, where on-demand conversion is enabled. This is what I used following your inspiring example, and it seems to be working. 

_on the server_ `ondemand.midx`
```
<dataset typename="IdxMultipleDataset">
  <dataset name="A" permissions="public" url="file:///ondemand_datasetA.idx"/>
  <dataset name="B" permissions="public" url="file:///ondemand_datasetB.idx"/>
</dataset>
```

_on the server_ `visus_server.config`
```
  <dataset name="ondemand_midx"        url="file:///ondemand.midx" >
    <access name="MultipleAccess" type="MultipleAccess">
      <A name="Multiplex" type="multiplex">
        <access chmod="r" type="disk" url="file:///ondemand_datasetA.idx" />
        <access chmod="r" ondemand="external" path="http://localhost:42299/convert" type="ondemandaccess" url="file:///ondemand_datasetA.idx" />
        <access chmod="r" type="disk" url="file:///ondemand_datasetA.idx" />
      </A>
      <B name="Multiplex" type="multiplex">
        <access chmod="r" type="disk" url="file:///ondemand_datasetB.idx" />
        <access chmod="r" ondemand="external" path="http://localhost:42299/convert" type="ondemandaccess" url="file:///ondemand_datasetB.idx" />
        <access chmod="r" type="disk" url="file:///ondemand_datasetB.idx" />
      </B>
    </access>
  </dataset>
```

and _on the client_ `visus_client.config`
```
      <dataset name="ondemand_midx"        url="$(server)ondemand_midx" >
			  <call template="CreateLogos" />
		    <access name="CacheComputation" type="multiplex">
			    <access compression="zip" dir="$(VisusCacheDirectory)/ondemand_midx/computation" name="ondemand_midx_test" nsamples="65536" type="DiskAccess" />
			    <access chmod="r" compression="zip" type="network" />
		    </access>
		    <access name="CacheDatasets" type="MultipleAccess">
			    <A type="multiplex">
				    <access chmod="rw" type="disk" url="file://$(VisusCacheDirectory)/ondemand_midx/A/visus.idx" />
				    <access chmod="r" compression="zip" type="network" url="$(server)ondemand_midx/A" />
			    </A>
			    <B type="multiplex">
				    <access chmod="rw" type="disk" url="file://$(VisusCacheDirectory)/ondemand_midx/B/visus.idx" />
				    <access chmod="r" compression="zip" type="network" url="$(server)ondemand_midx/B" />
			    </B>
		    </access>
      </dataset>
```

**Comment by cchriste** [comment]
UPDATE: this is only _partially_ working, for the *CacheComputation* case on the client. 
But for the *CacheDatasets* case it is not using the access specified on the server. 

This can be confirmed by simply loading the child dataset directly: **http://feedback.llnl.gov/mod_visus?dataset=ondemand_midx/A**

**Comment by scrgiorgio** [comment]
how do you specify the "CacheDatasets" on the server? I think the server will use the first one, no matter what you do.

**Comment by cchriste** [comment]
I explained every detail of my configuration. CacheDatasets is in the client config as you can see.

**Comment by scrgiorgio** [comment]
I don't get it. 

You say "But for the CacheDatasets case it is not using the access specified on the server.".... this is confusing. From the client you cannot specify what access will be used on the server side. Where are you specifying it?

And also when you say "This can be confirmed by simply loading the child dataset directly: http://feedback.llnl.gov/mod_visus?dataset=ondemand_midx/A". This is wrong. The "ondemand_midx/A" is a different/single/atomic dataset (automatically exposed by the midx, but it can exists as a standalone dataset) and there is no way the server will know that it should use some "portion"/child of the MultipleAccess. Example: what if ondemand_midx/A is used by several MIDX?

**Comment by cchriste** [comment]
I understand about the client which is why I noted that loading directly
still fails. The point is that ondemand_midx/A does not use the access
described for it on the server, but instead only reads the .idx from the
server directly. Because of this time steps that aren't already converted
never get converted.

Maybe there is something additional that must be described in the server
itself such as another level of multiple dataset? But nothing I've tried
seems to work.

**Comment by cchriste** [comment]
Basically, if you load ondemand_midx from the server it works (the specified access on the server is used) but if you try to load one of the children directly (ex: ondemand_midx/A) then the access is ignored. 

The client configuration itself does not seem relevant to this problem.

**Comment by scrgiorgio** [comment]
"if you try to load one of the children directly (ex: ondemand_midx/A) then the access is ignored."
yes this is the current behaviour.
Maybe you want to add something like (but not sure if it works):

<dataset name="ondemand_midx/A"        url="..." >
    <access ...your access here..../>
  </dataset>

**Comment by cchriste** [comment]
This doesn't work.

**Comment by cchriste** [comment]
Why is the access ignored when the dataset is requested directly? What are the consequences of changing this behavior?

**Comment by scrgiorgio** [comment]
This issue was moved to sci-visus/nvisusio#451

**Comment by scrgiorgio** [comment]
The answer is very complicate.

Just to give an hint: a dataset in the visus.config file contains an inner
<access> section.

And this <access> section can contain several child-accesses for its
child-datasets. But this information is 'nested' and 'hidden' (==not
exposed at the root level).

If you want to expose it, it must be at root level (as I was suggesting in
my last post).


2016-03-17 6:09 GMT+01:00 Cameron Christensen <notifications@github.com>:

**Comment by cchriste** [comment]
I tried your suggestion, with both same names and different names, but it didn't work as I said.
Can you please try to demonstrate a functional example?
