### ISSUE TITLE
midx of midx simple syntax no longer working 

### ISSUE THREAD

**Issue by cchriste** [sci-visus/visus-issues#367]
For midxofmidx.midx (in <nvisusio>/docs/examples/midx):
```
fails=input.first.A['pressure'];
works=input.first['output=input.A.pressure;'];
```

According to this commit the `fails` syntax should work:
https://github.com/sci-visus/nvisusio/commit/a1337671c78949051baa0a6d68f5cdb8ed416eb0#diff-d1c4012814df446b5db52d2e6b8ecd64

The other syntax becomes very confusing with almost any interesting example, including the default script when a midx is loaded that only averages the first field of all ensemble members:

```
f0=input.first['\
	\
	        args=[];\
	        for (var T=0;T<=9;T++)\
	        {\
	          args[args.length]=input.A[\"temperature?time=\"+T];\
	          args[args.length]=input.B[\"temperature?time=\"+T];\
	          args[args.length]=input.C[\"temperature?time=\"+T];\
	          args[args.length]=input.D[\"temperature?time=\"+T];\
	        }\
	        output=Visus.Array.avg(args);\
	      '];
f1=input.second['\
	f0=input.A.temperature;\
	f1=input.B.temperature;\
	f2=input.C.temperature;\
	f3=input.D.temperature;\
	output=Visus.Array.avg([f0,f1,f2,f3]);\
	'];
output=Visus.Array.avg([f0,f1]);
```

**Comment by scrgiorgio** [comment]
We are really pushing the home-made Javascript to its limit.
But let's try: 
https://github.com/sci-visus/nvisusio/commit/82804729aa73c5839a54efa42fac85736ac359da

**Comment by cchriste** [comment]
That seems to work.
