### ISSUE TITLE
user timer or external callback to periodically publish computation

### ISSUE THREAD

**Issue by cchriste** [sci-visus/visus-issues#371]
For _Scripting_ processing, there currently exists a callback-based method to publish intermediate computation results to the dataflow when the *doPublish()* keyword is encountered in a script. 

For _Fieldname_ processing, I implemented a similar method that suspends processing and publishes current results, but this is too tricky and probably very fragile.

After talking with @pascucci we believe it may be possible to utilize a simpler timer-based technique for both methods that simply publishes periodically. This could be implemented as a timer or even an external callback mechanism, either way 1) locking the script's output field(s), 2) publishing them, 3) unlocking them. 

As implied by 1,2,3 aboce, we would like to be able to explicitly declare multiple fields to be published. In this manner the output fields would also be initialized so they would be valid anytime they are published.

The idea is that the user shouldn't be required to explicitly decide when to publish partial results, but instead the application can determine the best times and do it automatically.

**Comment by scrgiorgio** [comment]
I'm not following, I need an example, possibly using the midxofmidx.
(NOTE: are you sure that the timer solution could work with nested midx?)

**Comment by cchriste** [comment]
Not sure it can work at all, but Valerio thinks it can. Maybe you can chat
with him about it for more clarity. I think the issue you bring up is a
legit concern. All those timers and locks could easily get out of hand. We
just wanted a method that doesn't require the code to manually call
doPublish.

**Comment by scrgiorgio** [comment]
Ok I will try to talk to Valerio asap.
But just to understand: if you had to write the timer-stuff in javascript
how it would be? I need to "visualize" it

2016-03-16 19:05 GMT+01:00 Cameron Christensen <notifications@github.com>:

**Comment by scrgiorgio** [comment]
This issue was moved to sci-visus/nvisusio#449
