### ISSUE TITLE
show representation of palette with ranges displayed in scene 

### ISSUE THREAD

**Issue by cchriste** [sci-visus/visus-issues#372]
This was a request from the climate team when we demoed at LLNL a couple weeks ago.
This feature is requested again and again. In the latest demo the scientist said *I can't use this. It is worthless without showing the ranges*.

**Comment by cchriste** [comment]
Assigning to @scrgiorgio since at some point this was added and later was removed, so he may know why.

**Comment by scrgiorgio** [comment]
This issue was moved to sci-visus/nvisusio#448
