### ISSUE TITLE
new nodes should be inserted downstream of Scripting node

### ISSUE THREAD

**Issue by cchriste** [sci-visus/visus-issues#373]
For example, Marching Cube, Statistics, etc. 
Currently these nodes are inserted directly after the query, so there is no way to perform processing during the dataflow except for the default of Rendering. This screenshot shows the current situation. The desired dataflow would have attached the Scripting and Marching Cube after the Scripting.
![screen shot 2016-03-17 at 5 21 21 pm](https://cloud.githubusercontent.com/assets/1260945/13864142/ea3026e0-ec64-11e5-9069-52ee4b910e5a.png)

**Comment by scrgiorgio** [comment]
This issue was moved to sci-visus/nvisusio#447
